//////////////////////////////////////////////////////////////////////////////
//
//            Copyright (c) 2019 Ronnie Brohn (EpicBrownie)      
//
//                Distributed under The MIT License (MIT).
//             (See accompanying file License.txt or copy at 
//                 https://opensource.org/licenses/MIT)
//
//           Please report any bugs, typos, or suggestions to
//              https://github.com/epicbrownie/Epic2/issues
//
//////////////////////////////////////////////////////////////////////////////

#include "VectorSwizzler_impl.hpp"

#include "../Vector.h"

//////////////////////////////////////////////////////////////////////////////

// Explicit Instantiations
namespace Epic::detail
{
	#pragma region 1-Index VectorSwizzlers

	template class VectorSwizzler<float, 1, 0>;

	template class VectorSwizzler<float, 2, 0>;
	template class VectorSwizzler<float, 2, 1>;

	template class VectorSwizzler<float, 3, 0>;
	template class VectorSwizzler<float, 3, 1>;
	template class VectorSwizzler<float, 3, 2>;

	template class VectorSwizzler<float, 4, 0>;
	template class VectorSwizzler<float, 4, 1>;
	template class VectorSwizzler<float, 4, 2>;
	template class VectorSwizzler<float, 4, 3>;

	template class VectorSwizzler<double, 1, 0>;

	template class VectorSwizzler<double, 2, 0>;
	template class VectorSwizzler<double, 2, 1>;

	template class VectorSwizzler<double, 3, 0>;
	template class VectorSwizzler<double, 3, 1>;
	template class VectorSwizzler<double, 3, 2>;

	template class VectorSwizzler<double, 4, 0>;
	template class VectorSwizzler<double, 4, 1>;
	template class VectorSwizzler<double, 4, 2>;
	template class VectorSwizzler<double, 4, 3>;

	#pragma endregion

	#pragma region 2-Index VectorSwizzlers

	template class VectorSwizzler<float, 1, 0, 0>;

	template class VectorSwizzler<float, 2, 0, 0>;
	template class VectorSwizzler<float, 2, 0, 1>;
	template class VectorSwizzler<float, 2, 1, 0>;
	template class VectorSwizzler<float, 2, 1, 1>;

	template class VectorSwizzler<float, 3, 0, 0>;
	template class VectorSwizzler<float, 3, 0, 1>;
	template class VectorSwizzler<float, 3, 0, 2>;
	template class VectorSwizzler<float, 3, 1, 0>;
	template class VectorSwizzler<float, 3, 1, 1>;
	template class VectorSwizzler<float, 3, 1, 2>;
	template class VectorSwizzler<float, 3, 2, 0>;
	template class VectorSwizzler<float, 3, 2, 1>;
	template class VectorSwizzler<float, 3, 2, 2>;

	template class VectorSwizzler<float, 4, 0, 0>;
	template class VectorSwizzler<float, 4, 0, 1>;
	template class VectorSwizzler<float, 4, 0, 2>;
	template class VectorSwizzler<float, 4, 0, 3>;
	template class VectorSwizzler<float, 4, 1, 0>;
	template class VectorSwizzler<float, 4, 1, 1>;
	template class VectorSwizzler<float, 4, 1, 2>;
	template class VectorSwizzler<float, 4, 1, 3>;
	template class VectorSwizzler<float, 4, 2, 0>;
	template class VectorSwizzler<float, 4, 2, 1>;
	template class VectorSwizzler<float, 4, 2, 2>;
	template class VectorSwizzler<float, 4, 2, 3>;
	template class VectorSwizzler<float, 4, 3, 0>;
	template class VectorSwizzler<float, 4, 3, 1>;
	template class VectorSwizzler<float, 4, 3, 2>;
	template class VectorSwizzler<float, 4, 3, 3>;

	template class VectorSwizzler<double, 1, 0, 0>;

	template class VectorSwizzler<double, 2, 0, 0>;
	template class VectorSwizzler<double, 2, 0, 1>;
	template class VectorSwizzler<double, 2, 1, 0>;
	template class VectorSwizzler<double, 2, 1, 1>;

	template class VectorSwizzler<double, 3, 0, 0>;
	template class VectorSwizzler<double, 3, 0, 1>;
	template class VectorSwizzler<double, 3, 0, 2>;
	template class VectorSwizzler<double, 3, 1, 0>;
	template class VectorSwizzler<double, 3, 1, 1>;
	template class VectorSwizzler<double, 3, 1, 2>;
	template class VectorSwizzler<double, 3, 2, 0>;
	template class VectorSwizzler<double, 3, 2, 1>;
	template class VectorSwizzler<double, 3, 2, 2>;

	template class VectorSwizzler<double, 4, 0, 0>;
	template class VectorSwizzler<double, 4, 0, 1>;
	template class VectorSwizzler<double, 4, 0, 2>;
	template class VectorSwizzler<double, 4, 0, 3>;
	template class VectorSwizzler<double, 4, 1, 0>;
	template class VectorSwizzler<double, 4, 1, 1>;
	template class VectorSwizzler<double, 4, 1, 2>;
	template class VectorSwizzler<double, 4, 1, 3>;
	template class VectorSwizzler<double, 4, 2, 0>;
	template class VectorSwizzler<double, 4, 2, 1>;
	template class VectorSwizzler<double, 4, 2, 2>;
	template class VectorSwizzler<double, 4, 2, 3>;
	template class VectorSwizzler<double, 4, 3, 0>;
	template class VectorSwizzler<double, 4, 3, 1>;
	template class VectorSwizzler<double, 4, 3, 2>;
	template class VectorSwizzler<double, 4, 3, 3>;

	#pragma endregion

	#pragma region 3-Index VectorSwizzlers

	template class VectorSwizzler<float, 1, 0, 0, 0>;

	template class VectorSwizzler<float, 2, 0, 0, 0>;
	template class VectorSwizzler<float, 2, 0, 0, 1>;
	template class VectorSwizzler<float, 2, 0, 1, 0>;
	template class VectorSwizzler<float, 2, 0, 1, 1>;
	template class VectorSwizzler<float, 2, 1, 0, 0>;
	template class VectorSwizzler<float, 2, 1, 0, 1>;
	template class VectorSwizzler<float, 2, 1, 1, 0>;
	template class VectorSwizzler<float, 2, 1, 1, 1>;

	template class VectorSwizzler<float, 3, 0, 0, 0>;
	template class VectorSwizzler<float, 3, 0, 0, 1>;
	template class VectorSwizzler<float, 3, 0, 0, 2>;
	template class VectorSwizzler<float, 3, 0, 1, 0>;
	template class VectorSwizzler<float, 3, 0, 1, 1>;
	template class VectorSwizzler<float, 3, 0, 1, 2>;
	template class VectorSwizzler<float, 3, 0, 2, 0>;
	template class VectorSwizzler<float, 3, 0, 2, 1>;
	template class VectorSwizzler<float, 3, 0, 2, 2>;
	template class VectorSwizzler<float, 3, 1, 0, 0>;
	template class VectorSwizzler<float, 3, 1, 0, 1>;
	template class VectorSwizzler<float, 3, 1, 0, 2>;
	template class VectorSwizzler<float, 3, 1, 1, 0>;
	template class VectorSwizzler<float, 3, 1, 1, 1>;
	template class VectorSwizzler<float, 3, 1, 1, 2>;
	template class VectorSwizzler<float, 3, 1, 2, 0>;
	template class VectorSwizzler<float, 3, 1, 2, 1>;
	template class VectorSwizzler<float, 3, 1, 2, 2>;
	template class VectorSwizzler<float, 3, 2, 0, 0>;
	template class VectorSwizzler<float, 3, 2, 0, 1>;
	template class VectorSwizzler<float, 3, 2, 0, 2>;
	template class VectorSwizzler<float, 3, 2, 1, 0>;
	template class VectorSwizzler<float, 3, 2, 1, 1>;
	template class VectorSwizzler<float, 3, 2, 1, 2>;
	template class VectorSwizzler<float, 3, 2, 2, 0>;
	template class VectorSwizzler<float, 3, 2, 2, 1>;
	template class VectorSwizzler<float, 3, 2, 2, 2>;

	template class VectorSwizzler<float, 4, 0, 0, 0>;
	template class VectorSwizzler<float, 4, 0, 0, 1>;
	template class VectorSwizzler<float, 4, 0, 0, 2>;
	template class VectorSwizzler<float, 4, 0, 0, 3>;
	template class VectorSwizzler<float, 4, 0, 1, 0>;
	template class VectorSwizzler<float, 4, 0, 1, 1>;
	template class VectorSwizzler<float, 4, 0, 1, 2>;
	template class VectorSwizzler<float, 4, 0, 1, 3>;
	template class VectorSwizzler<float, 4, 0, 2, 0>;
	template class VectorSwizzler<float, 4, 0, 2, 1>;
	template class VectorSwizzler<float, 4, 0, 2, 2>;
	template class VectorSwizzler<float, 4, 0, 2, 3>;
	template class VectorSwizzler<float, 4, 0, 3, 0>;
	template class VectorSwizzler<float, 4, 0, 3, 1>;
	template class VectorSwizzler<float, 4, 0, 3, 2>;
	template class VectorSwizzler<float, 4, 0, 3, 3>;
	template class VectorSwizzler<float, 4, 1, 0, 0>;
	template class VectorSwizzler<float, 4, 1, 0, 1>;
	template class VectorSwizzler<float, 4, 1, 0, 2>;
	template class VectorSwizzler<float, 4, 1, 0, 3>;
	template class VectorSwizzler<float, 4, 1, 1, 0>;
	template class VectorSwizzler<float, 4, 1, 1, 1>;
	template class VectorSwizzler<float, 4, 1, 1, 2>;
	template class VectorSwizzler<float, 4, 1, 1, 3>;
	template class VectorSwizzler<float, 4, 1, 2, 0>;
	template class VectorSwizzler<float, 4, 1, 2, 1>;
	template class VectorSwizzler<float, 4, 1, 2, 2>;
	template class VectorSwizzler<float, 4, 1, 2, 3>;
	template class VectorSwizzler<float, 4, 1, 3, 0>;
	template class VectorSwizzler<float, 4, 1, 3, 1>;
	template class VectorSwizzler<float, 4, 1, 3, 2>;
	template class VectorSwizzler<float, 4, 1, 3, 3>;
	template class VectorSwizzler<float, 4, 2, 0, 0>;
	template class VectorSwizzler<float, 4, 2, 0, 1>;
	template class VectorSwizzler<float, 4, 2, 0, 2>;
	template class VectorSwizzler<float, 4, 2, 0, 3>;
	template class VectorSwizzler<float, 4, 2, 1, 0>;
	template class VectorSwizzler<float, 4, 2, 1, 1>;
	template class VectorSwizzler<float, 4, 2, 1, 2>;
	template class VectorSwizzler<float, 4, 2, 1, 3>;
	template class VectorSwizzler<float, 4, 2, 2, 0>;
	template class VectorSwizzler<float, 4, 2, 2, 1>;
	template class VectorSwizzler<float, 4, 2, 2, 2>;
	template class VectorSwizzler<float, 4, 2, 2, 3>;
	template class VectorSwizzler<float, 4, 2, 3, 0>;
	template class VectorSwizzler<float, 4, 2, 3, 1>;
	template class VectorSwizzler<float, 4, 2, 3, 2>;
	template class VectorSwizzler<float, 4, 2, 3, 3>;
	template class VectorSwizzler<float, 4, 3, 0, 0>;
	template class VectorSwizzler<float, 4, 3, 0, 1>;
	template class VectorSwizzler<float, 4, 3, 0, 2>;
	template class VectorSwizzler<float, 4, 3, 0, 3>;
	template class VectorSwizzler<float, 4, 3, 1, 0>;
	template class VectorSwizzler<float, 4, 3, 1, 1>;
	template class VectorSwizzler<float, 4, 3, 1, 2>;
	template class VectorSwizzler<float, 4, 3, 1, 3>;
	template class VectorSwizzler<float, 4, 3, 2, 0>;
	template class VectorSwizzler<float, 4, 3, 2, 1>;
	template class VectorSwizzler<float, 4, 3, 2, 2>;
	template class VectorSwizzler<float, 4, 3, 2, 3>;
	template class VectorSwizzler<float, 4, 3, 3, 0>;
	template class VectorSwizzler<float, 4, 3, 3, 1>;
	template class VectorSwizzler<float, 4, 3, 3, 2>;
	template class VectorSwizzler<float, 4, 3, 3, 3>;

	template class VectorSwizzler<double, 1, 0, 0, 0>;

	template class VectorSwizzler<double, 2, 0, 0, 0>;
	template class VectorSwizzler<double, 2, 0, 0, 1>;
	template class VectorSwizzler<double, 2, 0, 1, 0>;
	template class VectorSwizzler<double, 2, 0, 1, 1>;
	template class VectorSwizzler<double, 2, 1, 0, 0>;
	template class VectorSwizzler<double, 2, 1, 0, 1>;
	template class VectorSwizzler<double, 2, 1, 1, 0>;
	template class VectorSwizzler<double, 2, 1, 1, 1>;

	template class VectorSwizzler<double, 3, 0, 0, 0>;
	template class VectorSwizzler<double, 3, 0, 0, 1>;
	template class VectorSwizzler<double, 3, 0, 0, 2>;
	template class VectorSwizzler<double, 3, 0, 1, 0>;
	template class VectorSwizzler<double, 3, 0, 1, 1>;
	template class VectorSwizzler<double, 3, 0, 1, 2>;
	template class VectorSwizzler<double, 3, 0, 2, 0>;
	template class VectorSwizzler<double, 3, 0, 2, 1>;
	template class VectorSwizzler<double, 3, 0, 2, 2>;
	template class VectorSwizzler<double, 3, 1, 0, 0>;
	template class VectorSwizzler<double, 3, 1, 0, 1>;
	template class VectorSwizzler<double, 3, 1, 0, 2>;
	template class VectorSwizzler<double, 3, 1, 1, 0>;
	template class VectorSwizzler<double, 3, 1, 1, 1>;
	template class VectorSwizzler<double, 3, 1, 1, 2>;
	template class VectorSwizzler<double, 3, 1, 2, 0>;
	template class VectorSwizzler<double, 3, 1, 2, 1>;
	template class VectorSwizzler<double, 3, 1, 2, 2>;
	template class VectorSwizzler<double, 3, 2, 0, 0>;
	template class VectorSwizzler<double, 3, 2, 0, 1>;
	template class VectorSwizzler<double, 3, 2, 0, 2>;
	template class VectorSwizzler<double, 3, 2, 1, 0>;
	template class VectorSwizzler<double, 3, 2, 1, 1>;
	template class VectorSwizzler<double, 3, 2, 1, 2>;
	template class VectorSwizzler<double, 3, 2, 2, 0>;
	template class VectorSwizzler<double, 3, 2, 2, 1>;
	template class VectorSwizzler<double, 3, 2, 2, 2>;

	template class VectorSwizzler<double, 4, 0, 0, 0>;
	template class VectorSwizzler<double, 4, 0, 0, 1>;
	template class VectorSwizzler<double, 4, 0, 0, 2>;
	template class VectorSwizzler<double, 4, 0, 0, 3>;
	template class VectorSwizzler<double, 4, 0, 1, 0>;
	template class VectorSwizzler<double, 4, 0, 1, 1>;
	template class VectorSwizzler<double, 4, 0, 1, 2>;
	template class VectorSwizzler<double, 4, 0, 1, 3>;
	template class VectorSwizzler<double, 4, 0, 2, 0>;
	template class VectorSwizzler<double, 4, 0, 2, 1>;
	template class VectorSwizzler<double, 4, 0, 2, 2>;
	template class VectorSwizzler<double, 4, 0, 2, 3>;
	template class VectorSwizzler<double, 4, 0, 3, 0>;
	template class VectorSwizzler<double, 4, 0, 3, 1>;
	template class VectorSwizzler<double, 4, 0, 3, 2>;
	template class VectorSwizzler<double, 4, 0, 3, 3>;
	template class VectorSwizzler<double, 4, 1, 0, 0>;
	template class VectorSwizzler<double, 4, 1, 0, 1>;
	template class VectorSwizzler<double, 4, 1, 0, 2>;
	template class VectorSwizzler<double, 4, 1, 0, 3>;
	template class VectorSwizzler<double, 4, 1, 1, 0>;
	template class VectorSwizzler<double, 4, 1, 1, 1>;
	template class VectorSwizzler<double, 4, 1, 1, 2>;
	template class VectorSwizzler<double, 4, 1, 1, 3>;
	template class VectorSwizzler<double, 4, 1, 2, 0>;
	template class VectorSwizzler<double, 4, 1, 2, 1>;
	template class VectorSwizzler<double, 4, 1, 2, 2>;
	template class VectorSwizzler<double, 4, 1, 2, 3>;
	template class VectorSwizzler<double, 4, 1, 3, 0>;
	template class VectorSwizzler<double, 4, 1, 3, 1>;
	template class VectorSwizzler<double, 4, 1, 3, 2>;
	template class VectorSwizzler<double, 4, 1, 3, 3>;
	template class VectorSwizzler<double, 4, 2, 0, 0>;
	template class VectorSwizzler<double, 4, 2, 0, 1>;
	template class VectorSwizzler<double, 4, 2, 0, 2>;
	template class VectorSwizzler<double, 4, 2, 0, 3>;
	template class VectorSwizzler<double, 4, 2, 1, 0>;
	template class VectorSwizzler<double, 4, 2, 1, 1>;
	template class VectorSwizzler<double, 4, 2, 1, 2>;
	template class VectorSwizzler<double, 4, 2, 1, 3>;
	template class VectorSwizzler<double, 4, 2, 2, 0>;
	template class VectorSwizzler<double, 4, 2, 2, 1>;
	template class VectorSwizzler<double, 4, 2, 2, 2>;
	template class VectorSwizzler<double, 4, 2, 2, 3>;
	template class VectorSwizzler<double, 4, 2, 3, 0>;
	template class VectorSwizzler<double, 4, 2, 3, 1>;
	template class VectorSwizzler<double, 4, 2, 3, 2>;
	template class VectorSwizzler<double, 4, 2, 3, 3>;
	template class VectorSwizzler<double, 4, 3, 0, 0>;
	template class VectorSwizzler<double, 4, 3, 0, 1>;
	template class VectorSwizzler<double, 4, 3, 0, 2>;
	template class VectorSwizzler<double, 4, 3, 0, 3>;
	template class VectorSwizzler<double, 4, 3, 1, 0>;
	template class VectorSwizzler<double, 4, 3, 1, 1>;
	template class VectorSwizzler<double, 4, 3, 1, 2>;
	template class VectorSwizzler<double, 4, 3, 1, 3>;
	template class VectorSwizzler<double, 4, 3, 2, 0>;
	template class VectorSwizzler<double, 4, 3, 2, 1>;
	template class VectorSwizzler<double, 4, 3, 2, 2>;
	template class VectorSwizzler<double, 4, 3, 2, 3>;
	template class VectorSwizzler<double, 4, 3, 3, 0>;
	template class VectorSwizzler<double, 4, 3, 3, 1>;
	template class VectorSwizzler<double, 4, 3, 3, 2>;
	template class VectorSwizzler<double, 4, 3, 3, 3>;

	#pragma endregion

	#pragma region 4-Index VectorSwizzlers

	template class VectorSwizzler<float, 1, 0, 0, 0, 0>;

	template class VectorSwizzler<float, 2, 0, 0, 0, 0>;
	template class VectorSwizzler<float, 2, 0, 0, 0, 1>;
	template class VectorSwizzler<float, 2, 0, 0, 1, 0>;
	template class VectorSwizzler<float, 2, 0, 0, 1, 1>;
	template class VectorSwizzler<float, 2, 0, 1, 0, 0>;
	template class VectorSwizzler<float, 2, 0, 1, 0, 1>;
	template class VectorSwizzler<float, 2, 0, 1, 1, 0>;
	template class VectorSwizzler<float, 2, 0, 1, 1, 1>;
	template class VectorSwizzler<float, 2, 1, 0, 0, 0>;
	template class VectorSwizzler<float, 2, 1, 0, 0, 1>;
	template class VectorSwizzler<float, 2, 1, 0, 1, 0>;
	template class VectorSwizzler<float, 2, 1, 0, 1, 1>;
	template class VectorSwizzler<float, 2, 1, 1, 0, 0>;
	template class VectorSwizzler<float, 2, 1, 1, 0, 1>;
	template class VectorSwizzler<float, 2, 1, 1, 1, 0>;
	template class VectorSwizzler<float, 2, 1, 1, 1, 1>;

	template class VectorSwizzler<float, 3, 0, 0, 0, 0>;
	template class VectorSwizzler<float, 3, 0, 0, 0, 1>;
	template class VectorSwizzler<float, 3, 0, 0, 0, 2>;
	template class VectorSwizzler<float, 3, 0, 0, 1, 0>;
	template class VectorSwizzler<float, 3, 0, 0, 1, 1>;
	template class VectorSwizzler<float, 3, 0, 0, 1, 2>;
	template class VectorSwizzler<float, 3, 0, 0, 2, 0>;
	template class VectorSwizzler<float, 3, 0, 0, 2, 1>;
	template class VectorSwizzler<float, 3, 0, 0, 2, 2>;
	template class VectorSwizzler<float, 3, 0, 1, 0, 0>;
	template class VectorSwizzler<float, 3, 0, 1, 0, 1>;
	template class VectorSwizzler<float, 3, 0, 1, 0, 2>;
	template class VectorSwizzler<float, 3, 0, 1, 1, 0>;
	template class VectorSwizzler<float, 3, 0, 1, 1, 1>;
	template class VectorSwizzler<float, 3, 0, 1, 1, 2>;
	template class VectorSwizzler<float, 3, 0, 1, 2, 0>;
	template class VectorSwizzler<float, 3, 0, 1, 2, 1>;
	template class VectorSwizzler<float, 3, 0, 1, 2, 2>;
	template class VectorSwizzler<float, 3, 0, 2, 0, 0>;
	template class VectorSwizzler<float, 3, 0, 2, 0, 1>;
	template class VectorSwizzler<float, 3, 0, 2, 0, 2>;
	template class VectorSwizzler<float, 3, 0, 2, 1, 0>;
	template class VectorSwizzler<float, 3, 0, 2, 1, 1>;
	template class VectorSwizzler<float, 3, 0, 2, 1, 2>;
	template class VectorSwizzler<float, 3, 0, 2, 2, 0>;
	template class VectorSwizzler<float, 3, 0, 2, 2, 1>;
	template class VectorSwizzler<float, 3, 0, 2, 2, 2>;
	template class VectorSwizzler<float, 3, 1, 0, 0, 0>;
	template class VectorSwizzler<float, 3, 1, 0, 0, 1>;
	template class VectorSwizzler<float, 3, 1, 0, 0, 2>;
	template class VectorSwizzler<float, 3, 1, 0, 1, 0>;
	template class VectorSwizzler<float, 3, 1, 0, 1, 1>;
	template class VectorSwizzler<float, 3, 1, 0, 1, 2>;
	template class VectorSwizzler<float, 3, 1, 0, 2, 0>;
	template class VectorSwizzler<float, 3, 1, 0, 2, 1>;
	template class VectorSwizzler<float, 3, 1, 0, 2, 2>;
	template class VectorSwizzler<float, 3, 1, 1, 0, 0>;
	template class VectorSwizzler<float, 3, 1, 1, 0, 1>;
	template class VectorSwizzler<float, 3, 1, 1, 0, 2>;
	template class VectorSwizzler<float, 3, 1, 1, 1, 0>;
	template class VectorSwizzler<float, 3, 1, 1, 1, 1>;
	template class VectorSwizzler<float, 3, 1, 1, 1, 2>;
	template class VectorSwizzler<float, 3, 1, 1, 2, 0>;
	template class VectorSwizzler<float, 3, 1, 1, 2, 1>;
	template class VectorSwizzler<float, 3, 1, 1, 2, 2>;
	template class VectorSwizzler<float, 3, 1, 2, 0, 0>;
	template class VectorSwizzler<float, 3, 1, 2, 0, 1>;
	template class VectorSwizzler<float, 3, 1, 2, 0, 2>;
	template class VectorSwizzler<float, 3, 1, 2, 1, 0>;
	template class VectorSwizzler<float, 3, 1, 2, 1, 1>;
	template class VectorSwizzler<float, 3, 1, 2, 1, 2>;
	template class VectorSwizzler<float, 3, 1, 2, 2, 0>;
	template class VectorSwizzler<float, 3, 1, 2, 2, 1>;
	template class VectorSwizzler<float, 3, 1, 2, 2, 2>;
	template class VectorSwizzler<float, 3, 2, 0, 0, 0>;
	template class VectorSwizzler<float, 3, 2, 0, 0, 1>;
	template class VectorSwizzler<float, 3, 2, 0, 0, 2>;
	template class VectorSwizzler<float, 3, 2, 0, 1, 0>;
	template class VectorSwizzler<float, 3, 2, 0, 1, 1>;
	template class VectorSwizzler<float, 3, 2, 0, 1, 2>;
	template class VectorSwizzler<float, 3, 2, 0, 2, 0>;
	template class VectorSwizzler<float, 3, 2, 0, 2, 1>;
	template class VectorSwizzler<float, 3, 2, 0, 2, 2>;
	template class VectorSwizzler<float, 3, 2, 1, 0, 0>;
	template class VectorSwizzler<float, 3, 2, 1, 0, 1>;
	template class VectorSwizzler<float, 3, 2, 1, 0, 2>;
	template class VectorSwizzler<float, 3, 2, 1, 1, 0>;
	template class VectorSwizzler<float, 3, 2, 1, 1, 1>;
	template class VectorSwizzler<float, 3, 2, 1, 1, 2>;
	template class VectorSwizzler<float, 3, 2, 1, 2, 0>;
	template class VectorSwizzler<float, 3, 2, 1, 2, 1>;
	template class VectorSwizzler<float, 3, 2, 1, 2, 2>;
	template class VectorSwizzler<float, 3, 2, 2, 0, 0>;
	template class VectorSwizzler<float, 3, 2, 2, 0, 1>;
	template class VectorSwizzler<float, 3, 2, 2, 0, 2>;
	template class VectorSwizzler<float, 3, 2, 2, 1, 0>;
	template class VectorSwizzler<float, 3, 2, 2, 1, 1>;
	template class VectorSwizzler<float, 3, 2, 2, 1, 2>;
	template class VectorSwizzler<float, 3, 2, 2, 2, 0>;
	template class VectorSwizzler<float, 3, 2, 2, 2, 1>;
	template class VectorSwizzler<float, 3, 2, 2, 2, 2>;

	template class VectorSwizzler<float, 4, 0, 0, 0, 0>;
	template class VectorSwizzler<float, 4, 0, 0, 0, 1>;
	template class VectorSwizzler<float, 4, 0, 0, 0, 2>;
	template class VectorSwizzler<float, 4, 0, 0, 0, 3>;
	template class VectorSwizzler<float, 4, 0, 0, 1, 0>;
	template class VectorSwizzler<float, 4, 0, 0, 1, 1>;
	template class VectorSwizzler<float, 4, 0, 0, 1, 2>;
	template class VectorSwizzler<float, 4, 0, 0, 1, 3>;
	template class VectorSwizzler<float, 4, 0, 0, 2, 0>;
	template class VectorSwizzler<float, 4, 0, 0, 2, 1>;
	template class VectorSwizzler<float, 4, 0, 0, 2, 2>;
	template class VectorSwizzler<float, 4, 0, 0, 2, 3>;
	template class VectorSwizzler<float, 4, 0, 0, 3, 0>;
	template class VectorSwizzler<float, 4, 0, 0, 3, 1>;
	template class VectorSwizzler<float, 4, 0, 0, 3, 2>;
	template class VectorSwizzler<float, 4, 0, 0, 3, 3>;
	template class VectorSwizzler<float, 4, 0, 1, 0, 0>;
	template class VectorSwizzler<float, 4, 0, 1, 0, 1>;
	template class VectorSwizzler<float, 4, 0, 1, 0, 2>;
	template class VectorSwizzler<float, 4, 0, 1, 0, 3>;
	template class VectorSwizzler<float, 4, 0, 1, 1, 0>;
	template class VectorSwizzler<float, 4, 0, 1, 1, 1>;
	template class VectorSwizzler<float, 4, 0, 1, 1, 2>;
	template class VectorSwizzler<float, 4, 0, 1, 1, 3>;
	template class VectorSwizzler<float, 4, 0, 1, 2, 0>;
	template class VectorSwizzler<float, 4, 0, 1, 2, 1>;
	template class VectorSwizzler<float, 4, 0, 1, 2, 2>;
	template class VectorSwizzler<float, 4, 0, 1, 2, 3>;
	template class VectorSwizzler<float, 4, 0, 1, 3, 0>;
	template class VectorSwizzler<float, 4, 0, 1, 3, 1>;
	template class VectorSwizzler<float, 4, 0, 1, 3, 2>;
	template class VectorSwizzler<float, 4, 0, 1, 3, 3>;
	template class VectorSwizzler<float, 4, 0, 2, 0, 0>;
	template class VectorSwizzler<float, 4, 0, 2, 0, 1>;
	template class VectorSwizzler<float, 4, 0, 2, 0, 2>;
	template class VectorSwizzler<float, 4, 0, 2, 0, 3>;
	template class VectorSwizzler<float, 4, 0, 2, 1, 0>;
	template class VectorSwizzler<float, 4, 0, 2, 1, 1>;
	template class VectorSwizzler<float, 4, 0, 2, 1, 2>;
	template class VectorSwizzler<float, 4, 0, 2, 1, 3>;
	template class VectorSwizzler<float, 4, 0, 2, 2, 0>;
	template class VectorSwizzler<float, 4, 0, 2, 2, 1>;
	template class VectorSwizzler<float, 4, 0, 2, 2, 2>;
	template class VectorSwizzler<float, 4, 0, 2, 2, 3>;
	template class VectorSwizzler<float, 4, 0, 2, 3, 0>;
	template class VectorSwizzler<float, 4, 0, 2, 3, 1>;
	template class VectorSwizzler<float, 4, 0, 2, 3, 2>;
	template class VectorSwizzler<float, 4, 0, 2, 3, 3>;
	template class VectorSwizzler<float, 4, 0, 3, 0, 0>;
	template class VectorSwizzler<float, 4, 0, 3, 0, 1>;
	template class VectorSwizzler<float, 4, 0, 3, 0, 2>;
	template class VectorSwizzler<float, 4, 0, 3, 0, 3>;
	template class VectorSwizzler<float, 4, 0, 3, 1, 0>;
	template class VectorSwizzler<float, 4, 0, 3, 1, 1>;
	template class VectorSwizzler<float, 4, 0, 3, 1, 2>;
	template class VectorSwizzler<float, 4, 0, 3, 1, 3>;
	template class VectorSwizzler<float, 4, 0, 3, 2, 0>;
	template class VectorSwizzler<float, 4, 0, 3, 2, 1>;
	template class VectorSwizzler<float, 4, 0, 3, 2, 2>;
	template class VectorSwizzler<float, 4, 0, 3, 2, 3>;
	template class VectorSwizzler<float, 4, 0, 3, 3, 0>;
	template class VectorSwizzler<float, 4, 0, 3, 3, 1>;
	template class VectorSwizzler<float, 4, 0, 3, 3, 2>;
	template class VectorSwizzler<float, 4, 0, 3, 3, 3>;
	template class VectorSwizzler<float, 4, 1, 0, 0, 0>;
	template class VectorSwizzler<float, 4, 1, 0, 0, 1>;
	template class VectorSwizzler<float, 4, 1, 0, 0, 2>;
	template class VectorSwizzler<float, 4, 1, 0, 0, 3>;
	template class VectorSwizzler<float, 4, 1, 0, 1, 0>;
	template class VectorSwizzler<float, 4, 1, 0, 1, 1>;
	template class VectorSwizzler<float, 4, 1, 0, 1, 2>;
	template class VectorSwizzler<float, 4, 1, 0, 1, 3>;
	template class VectorSwizzler<float, 4, 1, 0, 2, 0>;
	template class VectorSwizzler<float, 4, 1, 0, 2, 1>;
	template class VectorSwizzler<float, 4, 1, 0, 2, 2>;
	template class VectorSwizzler<float, 4, 1, 0, 2, 3>;
	template class VectorSwizzler<float, 4, 1, 0, 3, 0>;
	template class VectorSwizzler<float, 4, 1, 0, 3, 1>;
	template class VectorSwizzler<float, 4, 1, 0, 3, 2>;
	template class VectorSwizzler<float, 4, 1, 0, 3, 3>;
	template class VectorSwizzler<float, 4, 1, 1, 0, 0>;
	template class VectorSwizzler<float, 4, 1, 1, 0, 1>;
	template class VectorSwizzler<float, 4, 1, 1, 0, 2>;
	template class VectorSwizzler<float, 4, 1, 1, 0, 3>;
	template class VectorSwizzler<float, 4, 1, 1, 1, 0>;
	template class VectorSwizzler<float, 4, 1, 1, 1, 1>;
	template class VectorSwizzler<float, 4, 1, 1, 1, 2>;
	template class VectorSwizzler<float, 4, 1, 1, 1, 3>;
	template class VectorSwizzler<float, 4, 1, 1, 2, 0>;
	template class VectorSwizzler<float, 4, 1, 1, 2, 1>;
	template class VectorSwizzler<float, 4, 1, 1, 2, 2>;
	template class VectorSwizzler<float, 4, 1, 1, 2, 3>;
	template class VectorSwizzler<float, 4, 1, 1, 3, 0>;
	template class VectorSwizzler<float, 4, 1, 1, 3, 1>;
	template class VectorSwizzler<float, 4, 1, 1, 3, 2>;
	template class VectorSwizzler<float, 4, 1, 1, 3, 3>;
	template class VectorSwizzler<float, 4, 1, 2, 0, 0>;
	template class VectorSwizzler<float, 4, 1, 2, 0, 1>;
	template class VectorSwizzler<float, 4, 1, 2, 0, 2>;
	template class VectorSwizzler<float, 4, 1, 2, 0, 3>;
	template class VectorSwizzler<float, 4, 1, 2, 1, 0>;
	template class VectorSwizzler<float, 4, 1, 2, 1, 1>;
	template class VectorSwizzler<float, 4, 1, 2, 1, 2>;
	template class VectorSwizzler<float, 4, 1, 2, 1, 3>;
	template class VectorSwizzler<float, 4, 1, 2, 2, 0>;
	template class VectorSwizzler<float, 4, 1, 2, 2, 1>;
	template class VectorSwizzler<float, 4, 1, 2, 2, 2>;
	template class VectorSwizzler<float, 4, 1, 2, 2, 3>;
	template class VectorSwizzler<float, 4, 1, 2, 3, 0>;
	template class VectorSwizzler<float, 4, 1, 2, 3, 1>;
	template class VectorSwizzler<float, 4, 1, 2, 3, 2>;
	template class VectorSwizzler<float, 4, 1, 2, 3, 3>;
	template class VectorSwizzler<float, 4, 1, 3, 0, 0>;
	template class VectorSwizzler<float, 4, 1, 3, 0, 1>;
	template class VectorSwizzler<float, 4, 1, 3, 0, 2>;
	template class VectorSwizzler<float, 4, 1, 3, 0, 3>;
	template class VectorSwizzler<float, 4, 1, 3, 1, 0>;
	template class VectorSwizzler<float, 4, 1, 3, 1, 1>;
	template class VectorSwizzler<float, 4, 1, 3, 1, 2>;
	template class VectorSwizzler<float, 4, 1, 3, 1, 3>;
	template class VectorSwizzler<float, 4, 1, 3, 2, 0>;
	template class VectorSwizzler<float, 4, 1, 3, 2, 1>;
	template class VectorSwizzler<float, 4, 1, 3, 2, 2>;
	template class VectorSwizzler<float, 4, 1, 3, 2, 3>;
	template class VectorSwizzler<float, 4, 1, 3, 3, 0>;
	template class VectorSwizzler<float, 4, 1, 3, 3, 1>;
	template class VectorSwizzler<float, 4, 1, 3, 3, 2>;
	template class VectorSwizzler<float, 4, 1, 3, 3, 3>;
	template class VectorSwizzler<float, 4, 2, 0, 0, 0>;
	template class VectorSwizzler<float, 4, 2, 0, 0, 1>;
	template class VectorSwizzler<float, 4, 2, 0, 0, 2>;
	template class VectorSwizzler<float, 4, 2, 0, 0, 3>;
	template class VectorSwizzler<float, 4, 2, 0, 1, 0>;
	template class VectorSwizzler<float, 4, 2, 0, 1, 1>;
	template class VectorSwizzler<float, 4, 2, 0, 1, 2>;
	template class VectorSwizzler<float, 4, 2, 0, 1, 3>;
	template class VectorSwizzler<float, 4, 2, 0, 2, 0>;
	template class VectorSwizzler<float, 4, 2, 0, 2, 1>;
	template class VectorSwizzler<float, 4, 2, 0, 2, 2>;
	template class VectorSwizzler<float, 4, 2, 0, 2, 3>;
	template class VectorSwizzler<float, 4, 2, 0, 3, 0>;
	template class VectorSwizzler<float, 4, 2, 0, 3, 1>;
	template class VectorSwizzler<float, 4, 2, 0, 3, 2>;
	template class VectorSwizzler<float, 4, 2, 0, 3, 3>;
	template class VectorSwizzler<float, 4, 2, 1, 0, 0>;
	template class VectorSwizzler<float, 4, 2, 1, 0, 1>;
	template class VectorSwizzler<float, 4, 2, 1, 0, 2>;
	template class VectorSwizzler<float, 4, 2, 1, 0, 3>;
	template class VectorSwizzler<float, 4, 2, 1, 1, 0>;
	template class VectorSwizzler<float, 4, 2, 1, 1, 1>;
	template class VectorSwizzler<float, 4, 2, 1, 1, 2>;
	template class VectorSwizzler<float, 4, 2, 1, 1, 3>;
	template class VectorSwizzler<float, 4, 2, 1, 2, 0>;
	template class VectorSwizzler<float, 4, 2, 1, 2, 1>;
	template class VectorSwizzler<float, 4, 2, 1, 2, 2>;
	template class VectorSwizzler<float, 4, 2, 1, 2, 3>;
	template class VectorSwizzler<float, 4, 2, 1, 3, 0>;
	template class VectorSwizzler<float, 4, 2, 1, 3, 1>;
	template class VectorSwizzler<float, 4, 2, 1, 3, 2>;
	template class VectorSwizzler<float, 4, 2, 1, 3, 3>;
	template class VectorSwizzler<float, 4, 2, 2, 0, 0>;
	template class VectorSwizzler<float, 4, 2, 2, 0, 1>;
	template class VectorSwizzler<float, 4, 2, 2, 0, 2>;
	template class VectorSwizzler<float, 4, 2, 2, 0, 3>;
	template class VectorSwizzler<float, 4, 2, 2, 1, 0>;
	template class VectorSwizzler<float, 4, 2, 2, 1, 1>;
	template class VectorSwizzler<float, 4, 2, 2, 1, 2>;
	template class VectorSwizzler<float, 4, 2, 2, 1, 3>;
	template class VectorSwizzler<float, 4, 2, 2, 2, 0>;
	template class VectorSwizzler<float, 4, 2, 2, 2, 1>;
	template class VectorSwizzler<float, 4, 2, 2, 2, 2>;
	template class VectorSwizzler<float, 4, 2, 2, 2, 3>;
	template class VectorSwizzler<float, 4, 2, 2, 3, 0>;
	template class VectorSwizzler<float, 4, 2, 2, 3, 1>;
	template class VectorSwizzler<float, 4, 2, 2, 3, 2>;
	template class VectorSwizzler<float, 4, 2, 2, 3, 3>;
	template class VectorSwizzler<float, 4, 2, 3, 0, 0>;
	template class VectorSwizzler<float, 4, 2, 3, 0, 1>;
	template class VectorSwizzler<float, 4, 2, 3, 0, 2>;
	template class VectorSwizzler<float, 4, 2, 3, 0, 3>;
	template class VectorSwizzler<float, 4, 2, 3, 1, 0>;
	template class VectorSwizzler<float, 4, 2, 3, 1, 1>;
	template class VectorSwizzler<float, 4, 2, 3, 1, 2>;
	template class VectorSwizzler<float, 4, 2, 3, 1, 3>;
	template class VectorSwizzler<float, 4, 2, 3, 2, 0>;
	template class VectorSwizzler<float, 4, 2, 3, 2, 1>;
	template class VectorSwizzler<float, 4, 2, 3, 2, 2>;
	template class VectorSwizzler<float, 4, 2, 3, 2, 3>;
	template class VectorSwizzler<float, 4, 2, 3, 3, 0>;
	template class VectorSwizzler<float, 4, 2, 3, 3, 1>;
	template class VectorSwizzler<float, 4, 2, 3, 3, 2>;
	template class VectorSwizzler<float, 4, 2, 3, 3, 3>;
	template class VectorSwizzler<float, 4, 3, 0, 0, 0>;
	template class VectorSwizzler<float, 4, 3, 0, 0, 1>;
	template class VectorSwizzler<float, 4, 3, 0, 0, 2>;
	template class VectorSwizzler<float, 4, 3, 0, 0, 3>;
	template class VectorSwizzler<float, 4, 3, 0, 1, 0>;
	template class VectorSwizzler<float, 4, 3, 0, 1, 1>;
	template class VectorSwizzler<float, 4, 3, 0, 1, 2>;
	template class VectorSwizzler<float, 4, 3, 0, 1, 3>;
	template class VectorSwizzler<float, 4, 3, 0, 2, 0>;
	template class VectorSwizzler<float, 4, 3, 0, 2, 1>;
	template class VectorSwizzler<float, 4, 3, 0, 2, 2>;
	template class VectorSwizzler<float, 4, 3, 0, 2, 3>;
	template class VectorSwizzler<float, 4, 3, 0, 3, 0>;
	template class VectorSwizzler<float, 4, 3, 0, 3, 1>;
	template class VectorSwizzler<float, 4, 3, 0, 3, 2>;
	template class VectorSwizzler<float, 4, 3, 0, 3, 3>;
	template class VectorSwizzler<float, 4, 3, 1, 0, 0>;
	template class VectorSwizzler<float, 4, 3, 1, 0, 1>;
	template class VectorSwizzler<float, 4, 3, 1, 0, 2>;
	template class VectorSwizzler<float, 4, 3, 1, 0, 3>;
	template class VectorSwizzler<float, 4, 3, 1, 1, 0>;
	template class VectorSwizzler<float, 4, 3, 1, 1, 1>;
	template class VectorSwizzler<float, 4, 3, 1, 1, 2>;
	template class VectorSwizzler<float, 4, 3, 1, 1, 3>;
	template class VectorSwizzler<float, 4, 3, 1, 2, 0>;
	template class VectorSwizzler<float, 4, 3, 1, 2, 1>;
	template class VectorSwizzler<float, 4, 3, 1, 2, 2>;
	template class VectorSwizzler<float, 4, 3, 1, 2, 3>;
	template class VectorSwizzler<float, 4, 3, 1, 3, 0>;
	template class VectorSwizzler<float, 4, 3, 1, 3, 1>;
	template class VectorSwizzler<float, 4, 3, 1, 3, 2>;
	template class VectorSwizzler<float, 4, 3, 1, 3, 3>;
	template class VectorSwizzler<float, 4, 3, 2, 0, 0>;
	template class VectorSwizzler<float, 4, 3, 2, 0, 1>;
	template class VectorSwizzler<float, 4, 3, 2, 0, 2>;
	template class VectorSwizzler<float, 4, 3, 2, 0, 3>;
	template class VectorSwizzler<float, 4, 3, 2, 1, 0>;
	template class VectorSwizzler<float, 4, 3, 2, 1, 1>;
	template class VectorSwizzler<float, 4, 3, 2, 1, 2>;
	template class VectorSwizzler<float, 4, 3, 2, 1, 3>;
	template class VectorSwizzler<float, 4, 3, 2, 2, 0>;
	template class VectorSwizzler<float, 4, 3, 2, 2, 1>;
	template class VectorSwizzler<float, 4, 3, 2, 2, 2>;
	template class VectorSwizzler<float, 4, 3, 2, 2, 3>;
	template class VectorSwizzler<float, 4, 3, 2, 3, 0>;
	template class VectorSwizzler<float, 4, 3, 2, 3, 1>;
	template class VectorSwizzler<float, 4, 3, 2, 3, 2>;
	template class VectorSwizzler<float, 4, 3, 2, 3, 3>;
	template class VectorSwizzler<float, 4, 3, 3, 0, 0>;
	template class VectorSwizzler<float, 4, 3, 3, 0, 1>;
	template class VectorSwizzler<float, 4, 3, 3, 0, 2>;
	template class VectorSwizzler<float, 4, 3, 3, 0, 3>;
	template class VectorSwizzler<float, 4, 3, 3, 1, 0>;
	template class VectorSwizzler<float, 4, 3, 3, 1, 1>;
	template class VectorSwizzler<float, 4, 3, 3, 1, 2>;
	template class VectorSwizzler<float, 4, 3, 3, 1, 3>;
	template class VectorSwizzler<float, 4, 3, 3, 2, 0>;
	template class VectorSwizzler<float, 4, 3, 3, 2, 1>;
	template class VectorSwizzler<float, 4, 3, 3, 2, 2>;
	template class VectorSwizzler<float, 4, 3, 3, 2, 3>;
	template class VectorSwizzler<float, 4, 3, 3, 3, 0>;
	template class VectorSwizzler<float, 4, 3, 3, 3, 1>;
	template class VectorSwizzler<float, 4, 3, 3, 3, 2>;
	template class VectorSwizzler<float, 4, 3, 3, 3, 3>;

	template class VectorSwizzler<double, 1, 0, 0, 0, 0>;

	template class VectorSwizzler<double, 2, 0, 0, 0, 0>;
	template class VectorSwizzler<double, 2, 0, 0, 0, 1>;
	template class VectorSwizzler<double, 2, 0, 0, 1, 0>;
	template class VectorSwizzler<double, 2, 0, 0, 1, 1>;
	template class VectorSwizzler<double, 2, 0, 1, 0, 0>;
	template class VectorSwizzler<double, 2, 0, 1, 0, 1>;
	template class VectorSwizzler<double, 2, 0, 1, 1, 0>;
	template class VectorSwizzler<double, 2, 0, 1, 1, 1>;
	template class VectorSwizzler<double, 2, 1, 0, 0, 0>;
	template class VectorSwizzler<double, 2, 1, 0, 0, 1>;
	template class VectorSwizzler<double, 2, 1, 0, 1, 0>;
	template class VectorSwizzler<double, 2, 1, 0, 1, 1>;
	template class VectorSwizzler<double, 2, 1, 1, 0, 0>;
	template class VectorSwizzler<double, 2, 1, 1, 0, 1>;
	template class VectorSwizzler<double, 2, 1, 1, 1, 0>;
	template class VectorSwizzler<double, 2, 1, 1, 1, 1>;

	template class VectorSwizzler<double, 3, 0, 0, 0, 0>;
	template class VectorSwizzler<double, 3, 0, 0, 0, 1>;
	template class VectorSwizzler<double, 3, 0, 0, 0, 2>;
	template class VectorSwizzler<double, 3, 0, 0, 1, 0>;
	template class VectorSwizzler<double, 3, 0, 0, 1, 1>;
	template class VectorSwizzler<double, 3, 0, 0, 1, 2>;
	template class VectorSwizzler<double, 3, 0, 0, 2, 0>;
	template class VectorSwizzler<double, 3, 0, 0, 2, 1>;
	template class VectorSwizzler<double, 3, 0, 0, 2, 2>;
	template class VectorSwizzler<double, 3, 0, 1, 0, 0>;
	template class VectorSwizzler<double, 3, 0, 1, 0, 1>;
	template class VectorSwizzler<double, 3, 0, 1, 0, 2>;
	template class VectorSwizzler<double, 3, 0, 1, 1, 0>;
	template class VectorSwizzler<double, 3, 0, 1, 1, 1>;
	template class VectorSwizzler<double, 3, 0, 1, 1, 2>;
	template class VectorSwizzler<double, 3, 0, 1, 2, 0>;
	template class VectorSwizzler<double, 3, 0, 1, 2, 1>;
	template class VectorSwizzler<double, 3, 0, 1, 2, 2>;
	template class VectorSwizzler<double, 3, 0, 2, 0, 0>;
	template class VectorSwizzler<double, 3, 0, 2, 0, 1>;
	template class VectorSwizzler<double, 3, 0, 2, 0, 2>;
	template class VectorSwizzler<double, 3, 0, 2, 1, 0>;
	template class VectorSwizzler<double, 3, 0, 2, 1, 1>;
	template class VectorSwizzler<double, 3, 0, 2, 1, 2>;
	template class VectorSwizzler<double, 3, 0, 2, 2, 0>;
	template class VectorSwizzler<double, 3, 0, 2, 2, 1>;
	template class VectorSwizzler<double, 3, 0, 2, 2, 2>;
	template class VectorSwizzler<double, 3, 1, 0, 0, 0>;
	template class VectorSwizzler<double, 3, 1, 0, 0, 1>;
	template class VectorSwizzler<double, 3, 1, 0, 0, 2>;
	template class VectorSwizzler<double, 3, 1, 0, 1, 0>;
	template class VectorSwizzler<double, 3, 1, 0, 1, 1>;
	template class VectorSwizzler<double, 3, 1, 0, 1, 2>;
	template class VectorSwizzler<double, 3, 1, 0, 2, 0>;
	template class VectorSwizzler<double, 3, 1, 0, 2, 1>;
	template class VectorSwizzler<double, 3, 1, 0, 2, 2>;
	template class VectorSwizzler<double, 3, 1, 1, 0, 0>;
	template class VectorSwizzler<double, 3, 1, 1, 0, 1>;
	template class VectorSwizzler<double, 3, 1, 1, 0, 2>;
	template class VectorSwizzler<double, 3, 1, 1, 1, 0>;
	template class VectorSwizzler<double, 3, 1, 1, 1, 1>;
	template class VectorSwizzler<double, 3, 1, 1, 1, 2>;
	template class VectorSwizzler<double, 3, 1, 1, 2, 0>;
	template class VectorSwizzler<double, 3, 1, 1, 2, 1>;
	template class VectorSwizzler<double, 3, 1, 1, 2, 2>;
	template class VectorSwizzler<double, 3, 1, 2, 0, 0>;
	template class VectorSwizzler<double, 3, 1, 2, 0, 1>;
	template class VectorSwizzler<double, 3, 1, 2, 0, 2>;
	template class VectorSwizzler<double, 3, 1, 2, 1, 0>;
	template class VectorSwizzler<double, 3, 1, 2, 1, 1>;
	template class VectorSwizzler<double, 3, 1, 2, 1, 2>;
	template class VectorSwizzler<double, 3, 1, 2, 2, 0>;
	template class VectorSwizzler<double, 3, 1, 2, 2, 1>;
	template class VectorSwizzler<double, 3, 1, 2, 2, 2>;
	template class VectorSwizzler<double, 3, 2, 0, 0, 0>;
	template class VectorSwizzler<double, 3, 2, 0, 0, 1>;
	template class VectorSwizzler<double, 3, 2, 0, 0, 2>;
	template class VectorSwizzler<double, 3, 2, 0, 1, 0>;
	template class VectorSwizzler<double, 3, 2, 0, 1, 1>;
	template class VectorSwizzler<double, 3, 2, 0, 1, 2>;
	template class VectorSwizzler<double, 3, 2, 0, 2, 0>;
	template class VectorSwizzler<double, 3, 2, 0, 2, 1>;
	template class VectorSwizzler<double, 3, 2, 0, 2, 2>;
	template class VectorSwizzler<double, 3, 2, 1, 0, 0>;
	template class VectorSwizzler<double, 3, 2, 1, 0, 1>;
	template class VectorSwizzler<double, 3, 2, 1, 0, 2>;
	template class VectorSwizzler<double, 3, 2, 1, 1, 0>;
	template class VectorSwizzler<double, 3, 2, 1, 1, 1>;
	template class VectorSwizzler<double, 3, 2, 1, 1, 2>;
	template class VectorSwizzler<double, 3, 2, 1, 2, 0>;
	template class VectorSwizzler<double, 3, 2, 1, 2, 1>;
	template class VectorSwizzler<double, 3, 2, 1, 2, 2>;
	template class VectorSwizzler<double, 3, 2, 2, 0, 0>;
	template class VectorSwizzler<double, 3, 2, 2, 0, 1>;
	template class VectorSwizzler<double, 3, 2, 2, 0, 2>;
	template class VectorSwizzler<double, 3, 2, 2, 1, 0>;
	template class VectorSwizzler<double, 3, 2, 2, 1, 1>;
	template class VectorSwizzler<double, 3, 2, 2, 1, 2>;
	template class VectorSwizzler<double, 3, 2, 2, 2, 0>;
	template class VectorSwizzler<double, 3, 2, 2, 2, 1>;
	template class VectorSwizzler<double, 3, 2, 2, 2, 2>;

	template class VectorSwizzler<double, 4, 0, 0, 0, 0>;
	template class VectorSwizzler<double, 4, 0, 0, 0, 1>;
	template class VectorSwizzler<double, 4, 0, 0, 0, 2>;
	template class VectorSwizzler<double, 4, 0, 0, 0, 3>;
	template class VectorSwizzler<double, 4, 0, 0, 1, 0>;
	template class VectorSwizzler<double, 4, 0, 0, 1, 1>;
	template class VectorSwizzler<double, 4, 0, 0, 1, 2>;
	template class VectorSwizzler<double, 4, 0, 0, 1, 3>;
	template class VectorSwizzler<double, 4, 0, 0, 2, 0>;
	template class VectorSwizzler<double, 4, 0, 0, 2, 1>;
	template class VectorSwizzler<double, 4, 0, 0, 2, 2>;
	template class VectorSwizzler<double, 4, 0, 0, 2, 3>;
	template class VectorSwizzler<double, 4, 0, 0, 3, 0>;
	template class VectorSwizzler<double, 4, 0, 0, 3, 1>;
	template class VectorSwizzler<double, 4, 0, 0, 3, 2>;
	template class VectorSwizzler<double, 4, 0, 0, 3, 3>;
	template class VectorSwizzler<double, 4, 0, 1, 0, 0>;
	template class VectorSwizzler<double, 4, 0, 1, 0, 1>;
	template class VectorSwizzler<double, 4, 0, 1, 0, 2>;
	template class VectorSwizzler<double, 4, 0, 1, 0, 3>;
	template class VectorSwizzler<double, 4, 0, 1, 1, 0>;
	template class VectorSwizzler<double, 4, 0, 1, 1, 1>;
	template class VectorSwizzler<double, 4, 0, 1, 1, 2>;
	template class VectorSwizzler<double, 4, 0, 1, 1, 3>;
	template class VectorSwizzler<double, 4, 0, 1, 2, 0>;
	template class VectorSwizzler<double, 4, 0, 1, 2, 1>;
	template class VectorSwizzler<double, 4, 0, 1, 2, 2>;
	template class VectorSwizzler<double, 4, 0, 1, 2, 3>;
	template class VectorSwizzler<double, 4, 0, 1, 3, 0>;
	template class VectorSwizzler<double, 4, 0, 1, 3, 1>;
	template class VectorSwizzler<double, 4, 0, 1, 3, 2>;
	template class VectorSwizzler<double, 4, 0, 1, 3, 3>;
	template class VectorSwizzler<double, 4, 0, 2, 0, 0>;
	template class VectorSwizzler<double, 4, 0, 2, 0, 1>;
	template class VectorSwizzler<double, 4, 0, 2, 0, 2>;
	template class VectorSwizzler<double, 4, 0, 2, 0, 3>;
	template class VectorSwizzler<double, 4, 0, 2, 1, 0>;
	template class VectorSwizzler<double, 4, 0, 2, 1, 1>;
	template class VectorSwizzler<double, 4, 0, 2, 1, 2>;
	template class VectorSwizzler<double, 4, 0, 2, 1, 3>;
	template class VectorSwizzler<double, 4, 0, 2, 2, 0>;
	template class VectorSwizzler<double, 4, 0, 2, 2, 1>;
	template class VectorSwizzler<double, 4, 0, 2, 2, 2>;
	template class VectorSwizzler<double, 4, 0, 2, 2, 3>;
	template class VectorSwizzler<double, 4, 0, 2, 3, 0>;
	template class VectorSwizzler<double, 4, 0, 2, 3, 1>;
	template class VectorSwizzler<double, 4, 0, 2, 3, 2>;
	template class VectorSwizzler<double, 4, 0, 2, 3, 3>;
	template class VectorSwizzler<double, 4, 0, 3, 0, 0>;
	template class VectorSwizzler<double, 4, 0, 3, 0, 1>;
	template class VectorSwizzler<double, 4, 0, 3, 0, 2>;
	template class VectorSwizzler<double, 4, 0, 3, 0, 3>;
	template class VectorSwizzler<double, 4, 0, 3, 1, 0>;
	template class VectorSwizzler<double, 4, 0, 3, 1, 1>;
	template class VectorSwizzler<double, 4, 0, 3, 1, 2>;
	template class VectorSwizzler<double, 4, 0, 3, 1, 3>;
	template class VectorSwizzler<double, 4, 0, 3, 2, 0>;
	template class VectorSwizzler<double, 4, 0, 3, 2, 1>;
	template class VectorSwizzler<double, 4, 0, 3, 2, 2>;
	template class VectorSwizzler<double, 4, 0, 3, 2, 3>;
	template class VectorSwizzler<double, 4, 0, 3, 3, 0>;
	template class VectorSwizzler<double, 4, 0, 3, 3, 1>;
	template class VectorSwizzler<double, 4, 0, 3, 3, 2>;
	template class VectorSwizzler<double, 4, 0, 3, 3, 3>;
	template class VectorSwizzler<double, 4, 1, 0, 0, 0>;
	template class VectorSwizzler<double, 4, 1, 0, 0, 1>;
	template class VectorSwizzler<double, 4, 1, 0, 0, 2>;
	template class VectorSwizzler<double, 4, 1, 0, 0, 3>;
	template class VectorSwizzler<double, 4, 1, 0, 1, 0>;
	template class VectorSwizzler<double, 4, 1, 0, 1, 1>;
	template class VectorSwizzler<double, 4, 1, 0, 1, 2>;
	template class VectorSwizzler<double, 4, 1, 0, 1, 3>;
	template class VectorSwizzler<double, 4, 1, 0, 2, 0>;
	template class VectorSwizzler<double, 4, 1, 0, 2, 1>;
	template class VectorSwizzler<double, 4, 1, 0, 2, 2>;
	template class VectorSwizzler<double, 4, 1, 0, 2, 3>;
	template class VectorSwizzler<double, 4, 1, 0, 3, 0>;
	template class VectorSwizzler<double, 4, 1, 0, 3, 1>;
	template class VectorSwizzler<double, 4, 1, 0, 3, 2>;
	template class VectorSwizzler<double, 4, 1, 0, 3, 3>;
	template class VectorSwizzler<double, 4, 1, 1, 0, 0>;
	template class VectorSwizzler<double, 4, 1, 1, 0, 1>;
	template class VectorSwizzler<double, 4, 1, 1, 0, 2>;
	template class VectorSwizzler<double, 4, 1, 1, 0, 3>;
	template class VectorSwizzler<double, 4, 1, 1, 1, 0>;
	template class VectorSwizzler<double, 4, 1, 1, 1, 1>;
	template class VectorSwizzler<double, 4, 1, 1, 1, 2>;
	template class VectorSwizzler<double, 4, 1, 1, 1, 3>;
	template class VectorSwizzler<double, 4, 1, 1, 2, 0>;
	template class VectorSwizzler<double, 4, 1, 1, 2, 1>;
	template class VectorSwizzler<double, 4, 1, 1, 2, 2>;
	template class VectorSwizzler<double, 4, 1, 1, 2, 3>;
	template class VectorSwizzler<double, 4, 1, 1, 3, 0>;
	template class VectorSwizzler<double, 4, 1, 1, 3, 1>;
	template class VectorSwizzler<double, 4, 1, 1, 3, 2>;
	template class VectorSwizzler<double, 4, 1, 1, 3, 3>;
	template class VectorSwizzler<double, 4, 1, 2, 0, 0>;
	template class VectorSwizzler<double, 4, 1, 2, 0, 1>;
	template class VectorSwizzler<double, 4, 1, 2, 0, 2>;
	template class VectorSwizzler<double, 4, 1, 2, 0, 3>;
	template class VectorSwizzler<double, 4, 1, 2, 1, 0>;
	template class VectorSwizzler<double, 4, 1, 2, 1, 1>;
	template class VectorSwizzler<double, 4, 1, 2, 1, 2>;
	template class VectorSwizzler<double, 4, 1, 2, 1, 3>;
	template class VectorSwizzler<double, 4, 1, 2, 2, 0>;
	template class VectorSwizzler<double, 4, 1, 2, 2, 1>;
	template class VectorSwizzler<double, 4, 1, 2, 2, 2>;
	template class VectorSwizzler<double, 4, 1, 2, 2, 3>;
	template class VectorSwizzler<double, 4, 1, 2, 3, 0>;
	template class VectorSwizzler<double, 4, 1, 2, 3, 1>;
	template class VectorSwizzler<double, 4, 1, 2, 3, 2>;
	template class VectorSwizzler<double, 4, 1, 2, 3, 3>;
	template class VectorSwizzler<double, 4, 1, 3, 0, 0>;
	template class VectorSwizzler<double, 4, 1, 3, 0, 1>;
	template class VectorSwizzler<double, 4, 1, 3, 0, 2>;
	template class VectorSwizzler<double, 4, 1, 3, 0, 3>;
	template class VectorSwizzler<double, 4, 1, 3, 1, 0>;
	template class VectorSwizzler<double, 4, 1, 3, 1, 1>;
	template class VectorSwizzler<double, 4, 1, 3, 1, 2>;
	template class VectorSwizzler<double, 4, 1, 3, 1, 3>;
	template class VectorSwizzler<double, 4, 1, 3, 2, 0>;
	template class VectorSwizzler<double, 4, 1, 3, 2, 1>;
	template class VectorSwizzler<double, 4, 1, 3, 2, 2>;
	template class VectorSwizzler<double, 4, 1, 3, 2, 3>;
	template class VectorSwizzler<double, 4, 1, 3, 3, 0>;
	template class VectorSwizzler<double, 4, 1, 3, 3, 1>;
	template class VectorSwizzler<double, 4, 1, 3, 3, 2>;
	template class VectorSwizzler<double, 4, 1, 3, 3, 3>;
	template class VectorSwizzler<double, 4, 2, 0, 0, 0>;
	template class VectorSwizzler<double, 4, 2, 0, 0, 1>;
	template class VectorSwizzler<double, 4, 2, 0, 0, 2>;
	template class VectorSwizzler<double, 4, 2, 0, 0, 3>;
	template class VectorSwizzler<double, 4, 2, 0, 1, 0>;
	template class VectorSwizzler<double, 4, 2, 0, 1, 1>;
	template class VectorSwizzler<double, 4, 2, 0, 1, 2>;
	template class VectorSwizzler<double, 4, 2, 0, 1, 3>;
	template class VectorSwizzler<double, 4, 2, 0, 2, 0>;
	template class VectorSwizzler<double, 4, 2, 0, 2, 1>;
	template class VectorSwizzler<double, 4, 2, 0, 2, 2>;
	template class VectorSwizzler<double, 4, 2, 0, 2, 3>;
	template class VectorSwizzler<double, 4, 2, 0, 3, 0>;
	template class VectorSwizzler<double, 4, 2, 0, 3, 1>;
	template class VectorSwizzler<double, 4, 2, 0, 3, 2>;
	template class VectorSwizzler<double, 4, 2, 0, 3, 3>;
	template class VectorSwizzler<double, 4, 2, 1, 0, 0>;
	template class VectorSwizzler<double, 4, 2, 1, 0, 1>;
	template class VectorSwizzler<double, 4, 2, 1, 0, 2>;
	template class VectorSwizzler<double, 4, 2, 1, 0, 3>;
	template class VectorSwizzler<double, 4, 2, 1, 1, 0>;
	template class VectorSwizzler<double, 4, 2, 1, 1, 1>;
	template class VectorSwizzler<double, 4, 2, 1, 1, 2>;
	template class VectorSwizzler<double, 4, 2, 1, 1, 3>;
	template class VectorSwizzler<double, 4, 2, 1, 2, 0>;
	template class VectorSwizzler<double, 4, 2, 1, 2, 1>;
	template class VectorSwizzler<double, 4, 2, 1, 2, 2>;
	template class VectorSwizzler<double, 4, 2, 1, 2, 3>;
	template class VectorSwizzler<double, 4, 2, 1, 3, 0>;
	template class VectorSwizzler<double, 4, 2, 1, 3, 1>;
	template class VectorSwizzler<double, 4, 2, 1, 3, 2>;
	template class VectorSwizzler<double, 4, 2, 1, 3, 3>;
	template class VectorSwizzler<double, 4, 2, 2, 0, 0>;
	template class VectorSwizzler<double, 4, 2, 2, 0, 1>;
	template class VectorSwizzler<double, 4, 2, 2, 0, 2>;
	template class VectorSwizzler<double, 4, 2, 2, 0, 3>;
	template class VectorSwizzler<double, 4, 2, 2, 1, 0>;
	template class VectorSwizzler<double, 4, 2, 2, 1, 1>;
	template class VectorSwizzler<double, 4, 2, 2, 1, 2>;
	template class VectorSwizzler<double, 4, 2, 2, 1, 3>;
	template class VectorSwizzler<double, 4, 2, 2, 2, 0>;
	template class VectorSwizzler<double, 4, 2, 2, 2, 1>;
	template class VectorSwizzler<double, 4, 2, 2, 2, 2>;
	template class VectorSwizzler<double, 4, 2, 2, 2, 3>;
	template class VectorSwizzler<double, 4, 2, 2, 3, 0>;
	template class VectorSwizzler<double, 4, 2, 2, 3, 1>;
	template class VectorSwizzler<double, 4, 2, 2, 3, 2>;
	template class VectorSwizzler<double, 4, 2, 2, 3, 3>;
	template class VectorSwizzler<double, 4, 2, 3, 0, 0>;
	template class VectorSwizzler<double, 4, 2, 3, 0, 1>;
	template class VectorSwizzler<double, 4, 2, 3, 0, 2>;
	template class VectorSwizzler<double, 4, 2, 3, 0, 3>;
	template class VectorSwizzler<double, 4, 2, 3, 1, 0>;
	template class VectorSwizzler<double, 4, 2, 3, 1, 1>;
	template class VectorSwizzler<double, 4, 2, 3, 1, 2>;
	template class VectorSwizzler<double, 4, 2, 3, 1, 3>;
	template class VectorSwizzler<double, 4, 2, 3, 2, 0>;
	template class VectorSwizzler<double, 4, 2, 3, 2, 1>;
	template class VectorSwizzler<double, 4, 2, 3, 2, 2>;
	template class VectorSwizzler<double, 4, 2, 3, 2, 3>;
	template class VectorSwizzler<double, 4, 2, 3, 3, 0>;
	template class VectorSwizzler<double, 4, 2, 3, 3, 1>;
	template class VectorSwizzler<double, 4, 2, 3, 3, 2>;
	template class VectorSwizzler<double, 4, 2, 3, 3, 3>;
	template class VectorSwizzler<double, 4, 3, 0, 0, 0>;
	template class VectorSwizzler<double, 4, 3, 0, 0, 1>;
	template class VectorSwizzler<double, 4, 3, 0, 0, 2>;
	template class VectorSwizzler<double, 4, 3, 0, 0, 3>;
	template class VectorSwizzler<double, 4, 3, 0, 1, 0>;
	template class VectorSwizzler<double, 4, 3, 0, 1, 1>;
	template class VectorSwizzler<double, 4, 3, 0, 1, 2>;
	template class VectorSwizzler<double, 4, 3, 0, 1, 3>;
	template class VectorSwizzler<double, 4, 3, 0, 2, 0>;
	template class VectorSwizzler<double, 4, 3, 0, 2, 1>;
	template class VectorSwizzler<double, 4, 3, 0, 2, 2>;
	template class VectorSwizzler<double, 4, 3, 0, 2, 3>;
	template class VectorSwizzler<double, 4, 3, 0, 3, 0>;
	template class VectorSwizzler<double, 4, 3, 0, 3, 1>;
	template class VectorSwizzler<double, 4, 3, 0, 3, 2>;
	template class VectorSwizzler<double, 4, 3, 0, 3, 3>;
	template class VectorSwizzler<double, 4, 3, 1, 0, 0>;
	template class VectorSwizzler<double, 4, 3, 1, 0, 1>;
	template class VectorSwizzler<double, 4, 3, 1, 0, 2>;
	template class VectorSwizzler<double, 4, 3, 1, 0, 3>;
	template class VectorSwizzler<double, 4, 3, 1, 1, 0>;
	template class VectorSwizzler<double, 4, 3, 1, 1, 1>;
	template class VectorSwizzler<double, 4, 3, 1, 1, 2>;
	template class VectorSwizzler<double, 4, 3, 1, 1, 3>;
	template class VectorSwizzler<double, 4, 3, 1, 2, 0>;
	template class VectorSwizzler<double, 4, 3, 1, 2, 1>;
	template class VectorSwizzler<double, 4, 3, 1, 2, 2>;
	template class VectorSwizzler<double, 4, 3, 1, 2, 3>;
	template class VectorSwizzler<double, 4, 3, 1, 3, 0>;
	template class VectorSwizzler<double, 4, 3, 1, 3, 1>;
	template class VectorSwizzler<double, 4, 3, 1, 3, 2>;
	template class VectorSwizzler<double, 4, 3, 1, 3, 3>;
	template class VectorSwizzler<double, 4, 3, 2, 0, 0>;
	template class VectorSwizzler<double, 4, 3, 2, 0, 1>;
	template class VectorSwizzler<double, 4, 3, 2, 0, 2>;
	template class VectorSwizzler<double, 4, 3, 2, 0, 3>;
	template class VectorSwizzler<double, 4, 3, 2, 1, 0>;
	template class VectorSwizzler<double, 4, 3, 2, 1, 1>;
	template class VectorSwizzler<double, 4, 3, 2, 1, 2>;
	template class VectorSwizzler<double, 4, 3, 2, 1, 3>;
	template class VectorSwizzler<double, 4, 3, 2, 2, 0>;
	template class VectorSwizzler<double, 4, 3, 2, 2, 1>;
	template class VectorSwizzler<double, 4, 3, 2, 2, 2>;
	template class VectorSwizzler<double, 4, 3, 2, 2, 3>;
	template class VectorSwizzler<double, 4, 3, 2, 3, 0>;
	template class VectorSwizzler<double, 4, 3, 2, 3, 1>;
	template class VectorSwizzler<double, 4, 3, 2, 3, 2>;
	template class VectorSwizzler<double, 4, 3, 2, 3, 3>;
	template class VectorSwizzler<double, 4, 3, 3, 0, 0>;
	template class VectorSwizzler<double, 4, 3, 3, 0, 1>;
	template class VectorSwizzler<double, 4, 3, 3, 0, 2>;
	template class VectorSwizzler<double, 4, 3, 3, 0, 3>;
	template class VectorSwizzler<double, 4, 3, 3, 1, 0>;
	template class VectorSwizzler<double, 4, 3, 3, 1, 1>;
	template class VectorSwizzler<double, 4, 3, 3, 1, 2>;
	template class VectorSwizzler<double, 4, 3, 3, 1, 3>;
	template class VectorSwizzler<double, 4, 3, 3, 2, 0>;
	template class VectorSwizzler<double, 4, 3, 3, 2, 1>;
	template class VectorSwizzler<double, 4, 3, 3, 2, 2>;
	template class VectorSwizzler<double, 4, 3, 3, 2, 3>;
	template class VectorSwizzler<double, 4, 3, 3, 3, 0>;
	template class VectorSwizzler<double, 4, 3, 3, 3, 1>;
	template class VectorSwizzler<double, 4, 3, 3, 3, 2>;
	template class VectorSwizzler<double, 4, 3, 3, 3, 3>;

	#pragma endregion
}