//////////////////////////////////////////////////////////////////////////////
//
//            Copyright (c) 2019 Ronnie Brohn (EpicBrownie)      
//
//                Distributed under The MIT License (MIT).
//             (See accompanying file LICENSE or copy at 
//                 https://opensource.org/licenses/MIT)
//
//           Please report any bugs, typos, or suggestions to
//             https://github.com/unstable-sort/Epic/issues
//
//////////////////////////////////////////////////////////////////////////////

#pragma once

#include "VectorSwizzler_impl.hpp"

//////////////////////////////////////////////////////////////////////////////

// Externs
namespace Epic::detail
{
	#pragma region 1-Index VectorSwizzlers

	extern template class VectorSwizzler<float, 1, 0>;

	extern template class VectorSwizzler<float, 2, 0>;
	extern template class VectorSwizzler<float, 2, 1>;

	extern template class VectorSwizzler<float, 3, 0>;
	extern template class VectorSwizzler<float, 3, 1>;
	extern template class VectorSwizzler<float, 3, 2>;

	extern template class VectorSwizzler<float, 4, 0>;
	extern template class VectorSwizzler<float, 4, 1>;
	extern template class VectorSwizzler<float, 4, 2>;
	extern template class VectorSwizzler<float, 4, 3>;

	extern template class VectorSwizzler<double, 1, 0>;

	extern template class VectorSwizzler<double, 2, 0>;
	extern template class VectorSwizzler<double, 2, 1>;

	extern template class VectorSwizzler<double, 3, 0>;
	extern template class VectorSwizzler<double, 3, 1>;
	extern template class VectorSwizzler<double, 3, 2>;

	extern template class VectorSwizzler<double, 4, 0>;
	extern template class VectorSwizzler<double, 4, 1>;
	extern template class VectorSwizzler<double, 4, 2>;
	extern template class VectorSwizzler<double, 4, 3>;

	#pragma endregion

	#pragma region 2-Index VectorSwizzlers

	extern template class VectorSwizzler<float, 1, 0, 0>;

	extern template class VectorSwizzler<float, 2, 0, 0>;
	extern template class VectorSwizzler<float, 2, 0, 1>;
	extern template class VectorSwizzler<float, 2, 1, 0>;
	extern template class VectorSwizzler<float, 2, 1, 1>;

	extern template class VectorSwizzler<float, 3, 0, 0>;
	extern template class VectorSwizzler<float, 3, 0, 1>;
	extern template class VectorSwizzler<float, 3, 0, 2>;
	extern template class VectorSwizzler<float, 3, 1, 0>;
	extern template class VectorSwizzler<float, 3, 1, 1>;
	extern template class VectorSwizzler<float, 3, 1, 2>;
	extern template class VectorSwizzler<float, 3, 2, 0>;
	extern template class VectorSwizzler<float, 3, 2, 1>;
	extern template class VectorSwizzler<float, 3, 2, 2>;

	extern template class VectorSwizzler<float, 4, 0, 0>;
	extern template class VectorSwizzler<float, 4, 0, 1>;
	extern template class VectorSwizzler<float, 4, 0, 2>;
	extern template class VectorSwizzler<float, 4, 0, 3>;
	extern template class VectorSwizzler<float, 4, 1, 0>;
	extern template class VectorSwizzler<float, 4, 1, 1>;
	extern template class VectorSwizzler<float, 4, 1, 2>;
	extern template class VectorSwizzler<float, 4, 1, 3>;
	extern template class VectorSwizzler<float, 4, 2, 0>;
	extern template class VectorSwizzler<float, 4, 2, 1>;
	extern template class VectorSwizzler<float, 4, 2, 2>;
	extern template class VectorSwizzler<float, 4, 2, 3>;
	extern template class VectorSwizzler<float, 4, 3, 0>;
	extern template class VectorSwizzler<float, 4, 3, 1>;
	extern template class VectorSwizzler<float, 4, 3, 2>;
	extern template class VectorSwizzler<float, 4, 3, 3>;

	extern template class VectorSwizzler<double, 1, 0, 0>;

	extern template class VectorSwizzler<double, 2, 0, 0>;
	extern template class VectorSwizzler<double, 2, 0, 1>;
	extern template class VectorSwizzler<double, 2, 1, 0>;
	extern template class VectorSwizzler<double, 2, 1, 1>;

	extern template class VectorSwizzler<double, 3, 0, 0>;
	extern template class VectorSwizzler<double, 3, 0, 1>;
	extern template class VectorSwizzler<double, 3, 0, 2>;
	extern template class VectorSwizzler<double, 3, 1, 0>;
	extern template class VectorSwizzler<double, 3, 1, 1>;
	extern template class VectorSwizzler<double, 3, 1, 2>;
	extern template class VectorSwizzler<double, 3, 2, 0>;
	extern template class VectorSwizzler<double, 3, 2, 1>;
	extern template class VectorSwizzler<double, 3, 2, 2>;

	extern template class VectorSwizzler<double, 4, 0, 0>;
	extern template class VectorSwizzler<double, 4, 0, 1>;
	extern template class VectorSwizzler<double, 4, 0, 2>;
	extern template class VectorSwizzler<double, 4, 0, 3>;
	extern template class VectorSwizzler<double, 4, 1, 0>;
	extern template class VectorSwizzler<double, 4, 1, 1>;
	extern template class VectorSwizzler<double, 4, 1, 2>;
	extern template class VectorSwizzler<double, 4, 1, 3>;
	extern template class VectorSwizzler<double, 4, 2, 0>;
	extern template class VectorSwizzler<double, 4, 2, 1>;
	extern template class VectorSwizzler<double, 4, 2, 2>;
	extern template class VectorSwizzler<double, 4, 2, 3>;
	extern template class VectorSwizzler<double, 4, 3, 0>;
	extern template class VectorSwizzler<double, 4, 3, 1>;
	extern template class VectorSwizzler<double, 4, 3, 2>;
	extern template class VectorSwizzler<double, 4, 3, 3>;

	#pragma endregion

	#pragma region 3-Index VectorSwizzlers

	extern template class VectorSwizzler<float, 1, 0, 0, 0>;

	extern template class VectorSwizzler<float, 2, 0, 0, 0>;
	extern template class VectorSwizzler<float, 2, 0, 0, 1>;
	extern template class VectorSwizzler<float, 2, 0, 1, 0>;
	extern template class VectorSwizzler<float, 2, 0, 1, 1>;
	extern template class VectorSwizzler<float, 2, 1, 0, 0>;
	extern template class VectorSwizzler<float, 2, 1, 0, 1>;
	extern template class VectorSwizzler<float, 2, 1, 1, 0>;
	extern template class VectorSwizzler<float, 2, 1, 1, 1>;

	extern template class VectorSwizzler<float, 3, 0, 0, 0>;
	extern template class VectorSwizzler<float, 3, 0, 0, 1>;
	extern template class VectorSwizzler<float, 3, 0, 0, 2>; 
	extern template class VectorSwizzler<float, 3, 0, 1, 0>;
	extern template class VectorSwizzler<float, 3, 0, 1, 1>;
	extern template class VectorSwizzler<float, 3, 0, 1, 2>; 
	extern template class VectorSwizzler<float, 3, 0, 2, 0>;
	extern template class VectorSwizzler<float, 3, 0, 2, 1>;
	extern template class VectorSwizzler<float, 3, 0, 2, 2>;
	extern template class VectorSwizzler<float, 3, 1, 0, 0>;
	extern template class VectorSwizzler<float, 3, 1, 0, 1>;
	extern template class VectorSwizzler<float, 3, 1, 0, 2>;
	extern template class VectorSwizzler<float, 3, 1, 1, 0>;
	extern template class VectorSwizzler<float, 3, 1, 1, 1>;
	extern template class VectorSwizzler<float, 3, 1, 1, 2>;
	extern template class VectorSwizzler<float, 3, 1, 2, 0>;
	extern template class VectorSwizzler<float, 3, 1, 2, 1>;
	extern template class VectorSwizzler<float, 3, 1, 2, 2>;
	extern template class VectorSwizzler<float, 3, 2, 0, 0>;
	extern template class VectorSwizzler<float, 3, 2, 0, 1>;
	extern template class VectorSwizzler<float, 3, 2, 0, 2>;
	extern template class VectorSwizzler<float, 3, 2, 1, 0>;
	extern template class VectorSwizzler<float, 3, 2, 1, 1>;
	extern template class VectorSwizzler<float, 3, 2, 1, 2>;
	extern template class VectorSwizzler<float, 3, 2, 2, 0>;
	extern template class VectorSwizzler<float, 3, 2, 2, 1>;
	extern template class VectorSwizzler<float, 3, 2, 2, 2>;

	extern template class VectorSwizzler<float, 4, 0, 0, 0>;
	extern template class VectorSwizzler<float, 4, 0, 0, 1>;
	extern template class VectorSwizzler<float, 4, 0, 0, 2>;
	extern template class VectorSwizzler<float, 4, 0, 0, 3>;
	extern template class VectorSwizzler<float, 4, 0, 1, 0>;
	extern template class VectorSwizzler<float, 4, 0, 1, 1>;
	extern template class VectorSwizzler<float, 4, 0, 1, 2>;
	extern template class VectorSwizzler<float, 4, 0, 1, 3>;
	extern template class VectorSwizzler<float, 4, 0, 2, 0>;
	extern template class VectorSwizzler<float, 4, 0, 2, 1>;
	extern template class VectorSwizzler<float, 4, 0, 2, 2>;
	extern template class VectorSwizzler<float, 4, 0, 2, 3>;
	extern template class VectorSwizzler<float, 4, 0, 3, 0>;
	extern template class VectorSwizzler<float, 4, 0, 3, 1>;
	extern template class VectorSwizzler<float, 4, 0, 3, 2>;
	extern template class VectorSwizzler<float, 4, 0, 3, 3>;
	extern template class VectorSwizzler<float, 4, 1, 0, 0>;
	extern template class VectorSwizzler<float, 4, 1, 0, 1>;
	extern template class VectorSwizzler<float, 4, 1, 0, 2>;
	extern template class VectorSwizzler<float, 4, 1, 0, 3>;
	extern template class VectorSwizzler<float, 4, 1, 1, 0>;
	extern template class VectorSwizzler<float, 4, 1, 1, 1>;
	extern template class VectorSwizzler<float, 4, 1, 1, 2>;
	extern template class VectorSwizzler<float, 4, 1, 1, 3>;
	extern template class VectorSwizzler<float, 4, 1, 2, 0>;
	extern template class VectorSwizzler<float, 4, 1, 2, 1>;
	extern template class VectorSwizzler<float, 4, 1, 2, 2>;
	extern template class VectorSwizzler<float, 4, 1, 2, 3>;
	extern template class VectorSwizzler<float, 4, 1, 3, 0>;
	extern template class VectorSwizzler<float, 4, 1, 3, 1>;
	extern template class VectorSwizzler<float, 4, 1, 3, 2>;
	extern template class VectorSwizzler<float, 4, 1, 3, 3>;
	extern template class VectorSwizzler<float, 4, 2, 0, 0>;
	extern template class VectorSwizzler<float, 4, 2, 0, 1>;
	extern template class VectorSwizzler<float, 4, 2, 0, 2>;
	extern template class VectorSwizzler<float, 4, 2, 0, 3>;
	extern template class VectorSwizzler<float, 4, 2, 1, 0>;
	extern template class VectorSwizzler<float, 4, 2, 1, 1>;
	extern template class VectorSwizzler<float, 4, 2, 1, 2>;
	extern template class VectorSwizzler<float, 4, 2, 1, 3>;
	extern template class VectorSwizzler<float, 4, 2, 2, 0>;
	extern template class VectorSwizzler<float, 4, 2, 2, 1>;
	extern template class VectorSwizzler<float, 4, 2, 2, 2>;
	extern template class VectorSwizzler<float, 4, 2, 2, 3>;
	extern template class VectorSwizzler<float, 4, 2, 3, 0>;
	extern template class VectorSwizzler<float, 4, 2, 3, 1>;
	extern template class VectorSwizzler<float, 4, 2, 3, 2>;
	extern template class VectorSwizzler<float, 4, 2, 3, 3>;
	extern template class VectorSwizzler<float, 4, 3, 0, 0>;
	extern template class VectorSwizzler<float, 4, 3, 0, 1>;
	extern template class VectorSwizzler<float, 4, 3, 0, 2>;
	extern template class VectorSwizzler<float, 4, 3, 0, 3>;
	extern template class VectorSwizzler<float, 4, 3, 1, 0>;
	extern template class VectorSwizzler<float, 4, 3, 1, 1>;
	extern template class VectorSwizzler<float, 4, 3, 1, 2>;
	extern template class VectorSwizzler<float, 4, 3, 1, 3>;
	extern template class VectorSwizzler<float, 4, 3, 2, 0>;
	extern template class VectorSwizzler<float, 4, 3, 2, 1>;
	extern template class VectorSwizzler<float, 4, 3, 2, 2>;
	extern template class VectorSwizzler<float, 4, 3, 2, 3>;
	extern template class VectorSwizzler<float, 4, 3, 3, 0>;
	extern template class VectorSwizzler<float, 4, 3, 3, 1>;
	extern template class VectorSwizzler<float, 4, 3, 3, 2>;
	extern template class VectorSwizzler<float, 4, 3, 3, 3>;

	extern template class VectorSwizzler<double, 1, 0, 0, 0>;

	extern template class VectorSwizzler<double, 2, 0, 0, 0>;
	extern template class VectorSwizzler<double, 2, 0, 0, 1>;
	extern template class VectorSwizzler<double, 2, 0, 1, 0>;
	extern template class VectorSwizzler<double, 2, 0, 1, 1>;
	extern template class VectorSwizzler<double, 2, 1, 0, 0>;
	extern template class VectorSwizzler<double, 2, 1, 0, 1>;
	extern template class VectorSwizzler<double, 2, 1, 1, 0>;
	extern template class VectorSwizzler<double, 2, 1, 1, 1>;

	extern template class VectorSwizzler<double, 3, 0, 0, 0>;
	extern template class VectorSwizzler<double, 3, 0, 0, 1>;
	extern template class VectorSwizzler<double, 3, 0, 0, 2>;
	extern template class VectorSwizzler<double, 3, 0, 1, 0>;
	extern template class VectorSwizzler<double, 3, 0, 1, 1>;
	extern template class VectorSwizzler<double, 3, 0, 1, 2>;
	extern template class VectorSwizzler<double, 3, 0, 2, 0>;
	extern template class VectorSwizzler<double, 3, 0, 2, 1>;
	extern template class VectorSwizzler<double, 3, 0, 2, 2>;
	extern template class VectorSwizzler<double, 3, 1, 0, 0>;
	extern template class VectorSwizzler<double, 3, 1, 0, 1>;
	extern template class VectorSwizzler<double, 3, 1, 0, 2>;
	extern template class VectorSwizzler<double, 3, 1, 1, 0>;
	extern template class VectorSwizzler<double, 3, 1, 1, 1>;
	extern template class VectorSwizzler<double, 3, 1, 1, 2>;
	extern template class VectorSwizzler<double, 3, 1, 2, 0>;
	extern template class VectorSwizzler<double, 3, 1, 2, 1>;
	extern template class VectorSwizzler<double, 3, 1, 2, 2>;
	extern template class VectorSwizzler<double, 3, 2, 0, 0>;
	extern template class VectorSwizzler<double, 3, 2, 0, 1>;
	extern template class VectorSwizzler<double, 3, 2, 0, 2>;
	extern template class VectorSwizzler<double, 3, 2, 1, 0>;
	extern template class VectorSwizzler<double, 3, 2, 1, 1>;
	extern template class VectorSwizzler<double, 3, 2, 1, 2>;
	extern template class VectorSwizzler<double, 3, 2, 2, 0>;
	extern template class VectorSwizzler<double, 3, 2, 2, 1>;
	extern template class VectorSwizzler<double, 3, 2, 2, 2>;

	extern template class VectorSwizzler<double, 4, 0, 0, 0>;
	extern template class VectorSwizzler<double, 4, 0, 0, 1>;
	extern template class VectorSwizzler<double, 4, 0, 0, 2>;
	extern template class VectorSwizzler<double, 4, 0, 0, 3>;
	extern template class VectorSwizzler<double, 4, 0, 1, 0>;
	extern template class VectorSwizzler<double, 4, 0, 1, 1>;
	extern template class VectorSwizzler<double, 4, 0, 1, 2>;
	extern template class VectorSwizzler<double, 4, 0, 1, 3>;
	extern template class VectorSwizzler<double, 4, 0, 2, 0>;
	extern template class VectorSwizzler<double, 4, 0, 2, 1>;
	extern template class VectorSwizzler<double, 4, 0, 2, 2>;
	extern template class VectorSwizzler<double, 4, 0, 2, 3>;
	extern template class VectorSwizzler<double, 4, 0, 3, 0>;
	extern template class VectorSwizzler<double, 4, 0, 3, 1>;
	extern template class VectorSwizzler<double, 4, 0, 3, 2>;
	extern template class VectorSwizzler<double, 4, 0, 3, 3>;
	extern template class VectorSwizzler<double, 4, 1, 0, 0>;
	extern template class VectorSwizzler<double, 4, 1, 0, 1>;
	extern template class VectorSwizzler<double, 4, 1, 0, 2>;
	extern template class VectorSwizzler<double, 4, 1, 0, 3>;
	extern template class VectorSwizzler<double, 4, 1, 1, 0>;
	extern template class VectorSwizzler<double, 4, 1, 1, 1>;
	extern template class VectorSwizzler<double, 4, 1, 1, 2>;
	extern template class VectorSwizzler<double, 4, 1, 1, 3>;
	extern template class VectorSwizzler<double, 4, 1, 2, 0>;
	extern template class VectorSwizzler<double, 4, 1, 2, 1>;
	extern template class VectorSwizzler<double, 4, 1, 2, 2>;
	extern template class VectorSwizzler<double, 4, 1, 2, 3>;
	extern template class VectorSwizzler<double, 4, 1, 3, 0>;
	extern template class VectorSwizzler<double, 4, 1, 3, 1>;
	extern template class VectorSwizzler<double, 4, 1, 3, 2>;
	extern template class VectorSwizzler<double, 4, 1, 3, 3>;
	extern template class VectorSwizzler<double, 4, 2, 0, 0>;
	extern template class VectorSwizzler<double, 4, 2, 0, 1>;
	extern template class VectorSwizzler<double, 4, 2, 0, 2>;
	extern template class VectorSwizzler<double, 4, 2, 0, 3>;
	extern template class VectorSwizzler<double, 4, 2, 1, 0>;
	extern template class VectorSwizzler<double, 4, 2, 1, 1>;
	extern template class VectorSwizzler<double, 4, 2, 1, 2>;
	extern template class VectorSwizzler<double, 4, 2, 1, 3>;
	extern template class VectorSwizzler<double, 4, 2, 2, 0>;
	extern template class VectorSwizzler<double, 4, 2, 2, 1>;
	extern template class VectorSwizzler<double, 4, 2, 2, 2>;
	extern template class VectorSwizzler<double, 4, 2, 2, 3>;
	extern template class VectorSwizzler<double, 4, 2, 3, 0>;
	extern template class VectorSwizzler<double, 4, 2, 3, 1>;
	extern template class VectorSwizzler<double, 4, 2, 3, 2>;
	extern template class VectorSwizzler<double, 4, 2, 3, 3>;
	extern template class VectorSwizzler<double, 4, 3, 0, 0>;
	extern template class VectorSwizzler<double, 4, 3, 0, 1>;
	extern template class VectorSwizzler<double, 4, 3, 0, 2>;
	extern template class VectorSwizzler<double, 4, 3, 0, 3>;
	extern template class VectorSwizzler<double, 4, 3, 1, 0>;
	extern template class VectorSwizzler<double, 4, 3, 1, 1>;
	extern template class VectorSwizzler<double, 4, 3, 1, 2>;
	extern template class VectorSwizzler<double, 4, 3, 1, 3>;
	extern template class VectorSwizzler<double, 4, 3, 2, 0>;
	extern template class VectorSwizzler<double, 4, 3, 2, 1>;
	extern template class VectorSwizzler<double, 4, 3, 2, 2>;
	extern template class VectorSwizzler<double, 4, 3, 2, 3>;
	extern template class VectorSwizzler<double, 4, 3, 3, 0>;
	extern template class VectorSwizzler<double, 4, 3, 3, 1>;
	extern template class VectorSwizzler<double, 4, 3, 3, 2>;
	extern template class VectorSwizzler<double, 4, 3, 3, 3>;

	#pragma endregion

	#pragma region 4-Index VectorSwizzlers

	extern template class VectorSwizzler<float, 1, 0, 0, 0, 0>;

	extern template class VectorSwizzler<float, 2, 0, 0, 0, 0>;
	extern template class VectorSwizzler<float, 2, 0, 0, 0, 1>;
	extern template class VectorSwizzler<float, 2, 0, 0, 1, 0>;
	extern template class VectorSwizzler<float, 2, 0, 0, 1, 1>;
	extern template class VectorSwizzler<float, 2, 0, 1, 0, 0>;
	extern template class VectorSwizzler<float, 2, 0, 1, 0, 1>;
	extern template class VectorSwizzler<float, 2, 0, 1, 1, 0>;
	extern template class VectorSwizzler<float, 2, 0, 1, 1, 1>;
	extern template class VectorSwizzler<float, 2, 1, 0, 0, 0>;
	extern template class VectorSwizzler<float, 2, 1, 0, 0, 1>;
	extern template class VectorSwizzler<float, 2, 1, 0, 1, 0>;
	extern template class VectorSwizzler<float, 2, 1, 0, 1, 1>;
	extern template class VectorSwizzler<float, 2, 1, 1, 0, 0>;
	extern template class VectorSwizzler<float, 2, 1, 1, 0, 1>;
	extern template class VectorSwizzler<float, 2, 1, 1, 1, 0>;
	extern template class VectorSwizzler<float, 2, 1, 1, 1, 1>;

	extern template class VectorSwizzler<float, 3, 0, 0, 0, 0>;
	extern template class VectorSwizzler<float, 3, 0, 0, 0, 1>;
	extern template class VectorSwizzler<float, 3, 0, 0, 0, 2>;
	extern template class VectorSwizzler<float, 3, 0, 0, 1, 0>;
	extern template class VectorSwizzler<float, 3, 0, 0, 1, 1>;
	extern template class VectorSwizzler<float, 3, 0, 0, 1, 2>;
	extern template class VectorSwizzler<float, 3, 0, 0, 2, 0>;
	extern template class VectorSwizzler<float, 3, 0, 0, 2, 1>;
	extern template class VectorSwizzler<float, 3, 0, 0, 2, 2>;
	extern template class VectorSwizzler<float, 3, 0, 1, 0, 0>;
	extern template class VectorSwizzler<float, 3, 0, 1, 0, 1>;
	extern template class VectorSwizzler<float, 3, 0, 1, 0, 2>;
	extern template class VectorSwizzler<float, 3, 0, 1, 1, 0>;
	extern template class VectorSwizzler<float, 3, 0, 1, 1, 1>;
	extern template class VectorSwizzler<float, 3, 0, 1, 1, 2>;
	extern template class VectorSwizzler<float, 3, 0, 1, 2, 0>;
	extern template class VectorSwizzler<float, 3, 0, 1, 2, 1>;
	extern template class VectorSwizzler<float, 3, 0, 1, 2, 2>;
	extern template class VectorSwizzler<float, 3, 0, 2, 0, 0>;
	extern template class VectorSwizzler<float, 3, 0, 2, 0, 1>;
	extern template class VectorSwizzler<float, 3, 0, 2, 0, 2>;
	extern template class VectorSwizzler<float, 3, 0, 2, 1, 0>;
	extern template class VectorSwizzler<float, 3, 0, 2, 1, 1>;
	extern template class VectorSwizzler<float, 3, 0, 2, 1, 2>;
	extern template class VectorSwizzler<float, 3, 0, 2, 2, 0>;
	extern template class VectorSwizzler<float, 3, 0, 2, 2, 1>;
	extern template class VectorSwizzler<float, 3, 0, 2, 2, 2>;
	extern template class VectorSwizzler<float, 3, 1, 0, 0, 0>;
	extern template class VectorSwizzler<float, 3, 1, 0, 0, 1>;
	extern template class VectorSwizzler<float, 3, 1, 0, 0, 2>;
	extern template class VectorSwizzler<float, 3, 1, 0, 1, 0>;
	extern template class VectorSwizzler<float, 3, 1, 0, 1, 1>;
	extern template class VectorSwizzler<float, 3, 1, 0, 1, 2>;
	extern template class VectorSwizzler<float, 3, 1, 0, 2, 0>;
	extern template class VectorSwizzler<float, 3, 1, 0, 2, 1>;
	extern template class VectorSwizzler<float, 3, 1, 0, 2, 2>;
	extern template class VectorSwizzler<float, 3, 1, 1, 0, 0>;
	extern template class VectorSwizzler<float, 3, 1, 1, 0, 1>;
	extern template class VectorSwizzler<float, 3, 1, 1, 0, 2>;
	extern template class VectorSwizzler<float, 3, 1, 1, 1, 0>;
	extern template class VectorSwizzler<float, 3, 1, 1, 1, 1>;
	extern template class VectorSwizzler<float, 3, 1, 1, 1, 2>;
	extern template class VectorSwizzler<float, 3, 1, 1, 2, 0>;
	extern template class VectorSwizzler<float, 3, 1, 1, 2, 1>;
	extern template class VectorSwizzler<float, 3, 1, 1, 2, 2>;
	extern template class VectorSwizzler<float, 3, 1, 2, 0, 0>;
	extern template class VectorSwizzler<float, 3, 1, 2, 0, 1>;
	extern template class VectorSwizzler<float, 3, 1, 2, 0, 2>;
	extern template class VectorSwizzler<float, 3, 1, 2, 1, 0>;
	extern template class VectorSwizzler<float, 3, 1, 2, 1, 1>;
	extern template class VectorSwizzler<float, 3, 1, 2, 1, 2>;
	extern template class VectorSwizzler<float, 3, 1, 2, 2, 0>;
	extern template class VectorSwizzler<float, 3, 1, 2, 2, 1>;
	extern template class VectorSwizzler<float, 3, 1, 2, 2, 2>;
	extern template class VectorSwizzler<float, 3, 2, 0, 0, 0>;
	extern template class VectorSwizzler<float, 3, 2, 0, 0, 1>;
	extern template class VectorSwizzler<float, 3, 2, 0, 0, 2>;
	extern template class VectorSwizzler<float, 3, 2, 0, 1, 0>;
	extern template class VectorSwizzler<float, 3, 2, 0, 1, 1>;
	extern template class VectorSwizzler<float, 3, 2, 0, 1, 2>;
	extern template class VectorSwizzler<float, 3, 2, 0, 2, 0>;
	extern template class VectorSwizzler<float, 3, 2, 0, 2, 1>;
	extern template class VectorSwizzler<float, 3, 2, 0, 2, 2>;
	extern template class VectorSwizzler<float, 3, 2, 1, 0, 0>;
	extern template class VectorSwizzler<float, 3, 2, 1, 0, 1>;
	extern template class VectorSwizzler<float, 3, 2, 1, 0, 2>;
	extern template class VectorSwizzler<float, 3, 2, 1, 1, 0>;
	extern template class VectorSwizzler<float, 3, 2, 1, 1, 1>;
	extern template class VectorSwizzler<float, 3, 2, 1, 1, 2>;
	extern template class VectorSwizzler<float, 3, 2, 1, 2, 0>;
	extern template class VectorSwizzler<float, 3, 2, 1, 2, 1>;
	extern template class VectorSwizzler<float, 3, 2, 1, 2, 2>;
	extern template class VectorSwizzler<float, 3, 2, 2, 0, 0>;
	extern template class VectorSwizzler<float, 3, 2, 2, 0, 1>;
	extern template class VectorSwizzler<float, 3, 2, 2, 0, 2>;
	extern template class VectorSwizzler<float, 3, 2, 2, 1, 0>;
	extern template class VectorSwizzler<float, 3, 2, 2, 1, 1>;
	extern template class VectorSwizzler<float, 3, 2, 2, 1, 2>;
	extern template class VectorSwizzler<float, 3, 2, 2, 2, 0>;
	extern template class VectorSwizzler<float, 3, 2, 2, 2, 1>;
	extern template class VectorSwizzler<float, 3, 2, 2, 2, 2>;

	extern template class VectorSwizzler<float, 4, 0, 0, 0, 0>;
	extern template class VectorSwizzler<float, 4, 0, 0, 0, 1>;
	extern template class VectorSwizzler<float, 4, 0, 0, 0, 2>;
	extern template class VectorSwizzler<float, 4, 0, 0, 0, 3>;
	extern template class VectorSwizzler<float, 4, 0, 0, 1, 0>;
	extern template class VectorSwizzler<float, 4, 0, 0, 1, 1>;
	extern template class VectorSwizzler<float, 4, 0, 0, 1, 2>;
	extern template class VectorSwizzler<float, 4, 0, 0, 1, 3>;
	extern template class VectorSwizzler<float, 4, 0, 0, 2, 0>;
	extern template class VectorSwizzler<float, 4, 0, 0, 2, 1>;
	extern template class VectorSwizzler<float, 4, 0, 0, 2, 2>;
	extern template class VectorSwizzler<float, 4, 0, 0, 2, 3>;
	extern template class VectorSwizzler<float, 4, 0, 0, 3, 0>;
	extern template class VectorSwizzler<float, 4, 0, 0, 3, 1>;
	extern template class VectorSwizzler<float, 4, 0, 0, 3, 2>;
	extern template class VectorSwizzler<float, 4, 0, 0, 3, 3>;
	extern template class VectorSwizzler<float, 4, 0, 1, 0, 0>;
	extern template class VectorSwizzler<float, 4, 0, 1, 0, 1>;
	extern template class VectorSwizzler<float, 4, 0, 1, 0, 2>;
	extern template class VectorSwizzler<float, 4, 0, 1, 0, 3>;
	extern template class VectorSwizzler<float, 4, 0, 1, 1, 0>;
	extern template class VectorSwizzler<float, 4, 0, 1, 1, 1>;
	extern template class VectorSwizzler<float, 4, 0, 1, 1, 2>;
	extern template class VectorSwizzler<float, 4, 0, 1, 1, 3>;
	extern template class VectorSwizzler<float, 4, 0, 1, 2, 0>;
	extern template class VectorSwizzler<float, 4, 0, 1, 2, 1>;
	extern template class VectorSwizzler<float, 4, 0, 1, 2, 2>;
	extern template class VectorSwizzler<float, 4, 0, 1, 2, 3>;
	extern template class VectorSwizzler<float, 4, 0, 1, 3, 0>;
	extern template class VectorSwizzler<float, 4, 0, 1, 3, 1>;
	extern template class VectorSwizzler<float, 4, 0, 1, 3, 2>;
	extern template class VectorSwizzler<float, 4, 0, 1, 3, 3>;
	extern template class VectorSwizzler<float, 4, 0, 2, 0, 0>;
	extern template class VectorSwizzler<float, 4, 0, 2, 0, 1>;
	extern template class VectorSwizzler<float, 4, 0, 2, 0, 2>;
	extern template class VectorSwizzler<float, 4, 0, 2, 0, 3>;
	extern template class VectorSwizzler<float, 4, 0, 2, 1, 0>;
	extern template class VectorSwizzler<float, 4, 0, 2, 1, 1>;
	extern template class VectorSwizzler<float, 4, 0, 2, 1, 2>;
	extern template class VectorSwizzler<float, 4, 0, 2, 1, 3>;
	extern template class VectorSwizzler<float, 4, 0, 2, 2, 0>;
	extern template class VectorSwizzler<float, 4, 0, 2, 2, 1>;
	extern template class VectorSwizzler<float, 4, 0, 2, 2, 2>;
	extern template class VectorSwizzler<float, 4, 0, 2, 2, 3>;
	extern template class VectorSwizzler<float, 4, 0, 2, 3, 0>;
	extern template class VectorSwizzler<float, 4, 0, 2, 3, 1>;
	extern template class VectorSwizzler<float, 4, 0, 2, 3, 2>;
	extern template class VectorSwizzler<float, 4, 0, 2, 3, 3>;
	extern template class VectorSwizzler<float, 4, 0, 3, 0, 0>;
	extern template class VectorSwizzler<float, 4, 0, 3, 0, 1>;
	extern template class VectorSwizzler<float, 4, 0, 3, 0, 2>;
	extern template class VectorSwizzler<float, 4, 0, 3, 0, 3>;
	extern template class VectorSwizzler<float, 4, 0, 3, 1, 0>;
	extern template class VectorSwizzler<float, 4, 0, 3, 1, 1>;
	extern template class VectorSwizzler<float, 4, 0, 3, 1, 2>;
	extern template class VectorSwizzler<float, 4, 0, 3, 1, 3>;
	extern template class VectorSwizzler<float, 4, 0, 3, 2, 0>;
	extern template class VectorSwizzler<float, 4, 0, 3, 2, 1>;
	extern template class VectorSwizzler<float, 4, 0, 3, 2, 2>;
	extern template class VectorSwizzler<float, 4, 0, 3, 2, 3>;
	extern template class VectorSwizzler<float, 4, 0, 3, 3, 0>;
	extern template class VectorSwizzler<float, 4, 0, 3, 3, 1>;
	extern template class VectorSwizzler<float, 4, 0, 3, 3, 2>;
	extern template class VectorSwizzler<float, 4, 0, 3, 3, 3>;
	extern template class VectorSwizzler<float, 4, 1, 0, 0, 0>;
	extern template class VectorSwizzler<float, 4, 1, 0, 0, 1>;
	extern template class VectorSwizzler<float, 4, 1, 0, 0, 2>;
	extern template class VectorSwizzler<float, 4, 1, 0, 0, 3>;
	extern template class VectorSwizzler<float, 4, 1, 0, 1, 0>;
	extern template class VectorSwizzler<float, 4, 1, 0, 1, 1>;
	extern template class VectorSwizzler<float, 4, 1, 0, 1, 2>;
	extern template class VectorSwizzler<float, 4, 1, 0, 1, 3>;
	extern template class VectorSwizzler<float, 4, 1, 0, 2, 0>;
	extern template class VectorSwizzler<float, 4, 1, 0, 2, 1>;
	extern template class VectorSwizzler<float, 4, 1, 0, 2, 2>;
	extern template class VectorSwizzler<float, 4, 1, 0, 2, 3>;
	extern template class VectorSwizzler<float, 4, 1, 0, 3, 0>;
	extern template class VectorSwizzler<float, 4, 1, 0, 3, 1>;
	extern template class VectorSwizzler<float, 4, 1, 0, 3, 2>;
	extern template class VectorSwizzler<float, 4, 1, 0, 3, 3>;
	extern template class VectorSwizzler<float, 4, 1, 1, 0, 0>;
	extern template class VectorSwizzler<float, 4, 1, 1, 0, 1>;
	extern template class VectorSwizzler<float, 4, 1, 1, 0, 2>;
	extern template class VectorSwizzler<float, 4, 1, 1, 0, 3>;
	extern template class VectorSwizzler<float, 4, 1, 1, 1, 0>;
	extern template class VectorSwizzler<float, 4, 1, 1, 1, 1>;
	extern template class VectorSwizzler<float, 4, 1, 1, 1, 2>;
	extern template class VectorSwizzler<float, 4, 1, 1, 1, 3>;
	extern template class VectorSwizzler<float, 4, 1, 1, 2, 0>;
	extern template class VectorSwizzler<float, 4, 1, 1, 2, 1>;
	extern template class VectorSwizzler<float, 4, 1, 1, 2, 2>;
	extern template class VectorSwizzler<float, 4, 1, 1, 2, 3>;
	extern template class VectorSwizzler<float, 4, 1, 1, 3, 0>;
	extern template class VectorSwizzler<float, 4, 1, 1, 3, 1>;
	extern template class VectorSwizzler<float, 4, 1, 1, 3, 2>;
	extern template class VectorSwizzler<float, 4, 1, 1, 3, 3>;
	extern template class VectorSwizzler<float, 4, 1, 2, 0, 0>;
	extern template class VectorSwizzler<float, 4, 1, 2, 0, 1>;
	extern template class VectorSwizzler<float, 4, 1, 2, 0, 2>;
	extern template class VectorSwizzler<float, 4, 1, 2, 0, 3>;
	extern template class VectorSwizzler<float, 4, 1, 2, 1, 0>;
	extern template class VectorSwizzler<float, 4, 1, 2, 1, 1>;
	extern template class VectorSwizzler<float, 4, 1, 2, 1, 2>;
	extern template class VectorSwizzler<float, 4, 1, 2, 1, 3>;
	extern template class VectorSwizzler<float, 4, 1, 2, 2, 0>;
	extern template class VectorSwizzler<float, 4, 1, 2, 2, 1>;
	extern template class VectorSwizzler<float, 4, 1, 2, 2, 2>;
	extern template class VectorSwizzler<float, 4, 1, 2, 2, 3>;
	extern template class VectorSwizzler<float, 4, 1, 2, 3, 0>;
	extern template class VectorSwizzler<float, 4, 1, 2, 3, 1>;
	extern template class VectorSwizzler<float, 4, 1, 2, 3, 2>;
	extern template class VectorSwizzler<float, 4, 1, 2, 3, 3>;
	extern template class VectorSwizzler<float, 4, 1, 3, 0, 0>;
	extern template class VectorSwizzler<float, 4, 1, 3, 0, 1>;
	extern template class VectorSwizzler<float, 4, 1, 3, 0, 2>;
	extern template class VectorSwizzler<float, 4, 1, 3, 0, 3>;
	extern template class VectorSwizzler<float, 4, 1, 3, 1, 0>;
	extern template class VectorSwizzler<float, 4, 1, 3, 1, 1>;
	extern template class VectorSwizzler<float, 4, 1, 3, 1, 2>;
	extern template class VectorSwizzler<float, 4, 1, 3, 1, 3>;
	extern template class VectorSwizzler<float, 4, 1, 3, 2, 0>;
	extern template class VectorSwizzler<float, 4, 1, 3, 2, 1>;
	extern template class VectorSwizzler<float, 4, 1, 3, 2, 2>;
	extern template class VectorSwizzler<float, 4, 1, 3, 2, 3>;
	extern template class VectorSwizzler<float, 4, 1, 3, 3, 0>;
	extern template class VectorSwizzler<float, 4, 1, 3, 3, 1>;
	extern template class VectorSwizzler<float, 4, 1, 3, 3, 2>;
	extern template class VectorSwizzler<float, 4, 1, 3, 3, 3>;
	extern template class VectorSwizzler<float, 4, 2, 0, 0, 0>;
	extern template class VectorSwizzler<float, 4, 2, 0, 0, 1>;
	extern template class VectorSwizzler<float, 4, 2, 0, 0, 2>;
	extern template class VectorSwizzler<float, 4, 2, 0, 0, 3>;
	extern template class VectorSwizzler<float, 4, 2, 0, 1, 0>;
	extern template class VectorSwizzler<float, 4, 2, 0, 1, 1>;
	extern template class VectorSwizzler<float, 4, 2, 0, 1, 2>;
	extern template class VectorSwizzler<float, 4, 2, 0, 1, 3>;
	extern template class VectorSwizzler<float, 4, 2, 0, 2, 0>;
	extern template class VectorSwizzler<float, 4, 2, 0, 2, 1>;
	extern template class VectorSwizzler<float, 4, 2, 0, 2, 2>;
	extern template class VectorSwizzler<float, 4, 2, 0, 2, 3>;
	extern template class VectorSwizzler<float, 4, 2, 0, 3, 0>;
	extern template class VectorSwizzler<float, 4, 2, 0, 3, 1>;
	extern template class VectorSwizzler<float, 4, 2, 0, 3, 2>;
	extern template class VectorSwizzler<float, 4, 2, 0, 3, 3>;
	extern template class VectorSwizzler<float, 4, 2, 1, 0, 0>;
	extern template class VectorSwizzler<float, 4, 2, 1, 0, 1>;
	extern template class VectorSwizzler<float, 4, 2, 1, 0, 2>;
	extern template class VectorSwizzler<float, 4, 2, 1, 0, 3>;
	extern template class VectorSwizzler<float, 4, 2, 1, 1, 0>;
	extern template class VectorSwizzler<float, 4, 2, 1, 1, 1>;
	extern template class VectorSwizzler<float, 4, 2, 1, 1, 2>;
	extern template class VectorSwizzler<float, 4, 2, 1, 1, 3>;
	extern template class VectorSwizzler<float, 4, 2, 1, 2, 0>;
	extern template class VectorSwizzler<float, 4, 2, 1, 2, 1>;
	extern template class VectorSwizzler<float, 4, 2, 1, 2, 2>;
	extern template class VectorSwizzler<float, 4, 2, 1, 2, 3>;
	extern template class VectorSwizzler<float, 4, 2, 1, 3, 0>;
	extern template class VectorSwizzler<float, 4, 2, 1, 3, 1>;
	extern template class VectorSwizzler<float, 4, 2, 1, 3, 2>;
	extern template class VectorSwizzler<float, 4, 2, 1, 3, 3>;
	extern template class VectorSwizzler<float, 4, 2, 2, 0, 0>;
	extern template class VectorSwizzler<float, 4, 2, 2, 0, 1>;
	extern template class VectorSwizzler<float, 4, 2, 2, 0, 2>;
	extern template class VectorSwizzler<float, 4, 2, 2, 0, 3>;
	extern template class VectorSwizzler<float, 4, 2, 2, 1, 0>;
	extern template class VectorSwizzler<float, 4, 2, 2, 1, 1>;
	extern template class VectorSwizzler<float, 4, 2, 2, 1, 2>;
	extern template class VectorSwizzler<float, 4, 2, 2, 1, 3>;
	extern template class VectorSwizzler<float, 4, 2, 2, 2, 0>;
	extern template class VectorSwizzler<float, 4, 2, 2, 2, 1>;
	extern template class VectorSwizzler<float, 4, 2, 2, 2, 2>;
	extern template class VectorSwizzler<float, 4, 2, 2, 2, 3>;
	extern template class VectorSwizzler<float, 4, 2, 2, 3, 0>;
	extern template class VectorSwizzler<float, 4, 2, 2, 3, 1>;
	extern template class VectorSwizzler<float, 4, 2, 2, 3, 2>;
	extern template class VectorSwizzler<float, 4, 2, 2, 3, 3>;
	extern template class VectorSwizzler<float, 4, 2, 3, 0, 0>;
	extern template class VectorSwizzler<float, 4, 2, 3, 0, 1>;
	extern template class VectorSwizzler<float, 4, 2, 3, 0, 2>;
	extern template class VectorSwizzler<float, 4, 2, 3, 0, 3>;
	extern template class VectorSwizzler<float, 4, 2, 3, 1, 0>;
	extern template class VectorSwizzler<float, 4, 2, 3, 1, 1>;
	extern template class VectorSwizzler<float, 4, 2, 3, 1, 2>;
	extern template class VectorSwizzler<float, 4, 2, 3, 1, 3>;
	extern template class VectorSwizzler<float, 4, 2, 3, 2, 0>;
	extern template class VectorSwizzler<float, 4, 2, 3, 2, 1>;
	extern template class VectorSwizzler<float, 4, 2, 3, 2, 2>;
	extern template class VectorSwizzler<float, 4, 2, 3, 2, 3>;
	extern template class VectorSwizzler<float, 4, 2, 3, 3, 0>;
	extern template class VectorSwizzler<float, 4, 2, 3, 3, 1>;
	extern template class VectorSwizzler<float, 4, 2, 3, 3, 2>;
	extern template class VectorSwizzler<float, 4, 2, 3, 3, 3>;
	extern template class VectorSwizzler<float, 4, 3, 0, 0, 0>;
	extern template class VectorSwizzler<float, 4, 3, 0, 0, 1>;
	extern template class VectorSwizzler<float, 4, 3, 0, 0, 2>;
	extern template class VectorSwizzler<float, 4, 3, 0, 0, 3>;
	extern template class VectorSwizzler<float, 4, 3, 0, 1, 0>;
	extern template class VectorSwizzler<float, 4, 3, 0, 1, 1>;
	extern template class VectorSwizzler<float, 4, 3, 0, 1, 2>;
	extern template class VectorSwizzler<float, 4, 3, 0, 1, 3>;
	extern template class VectorSwizzler<float, 4, 3, 0, 2, 0>;
	extern template class VectorSwizzler<float, 4, 3, 0, 2, 1>;
	extern template class VectorSwizzler<float, 4, 3, 0, 2, 2>;
	extern template class VectorSwizzler<float, 4, 3, 0, 2, 3>;
	extern template class VectorSwizzler<float, 4, 3, 0, 3, 0>;
	extern template class VectorSwizzler<float, 4, 3, 0, 3, 1>;
	extern template class VectorSwizzler<float, 4, 3, 0, 3, 2>;
	extern template class VectorSwizzler<float, 4, 3, 0, 3, 3>;
	extern template class VectorSwizzler<float, 4, 3, 1, 0, 0>;
	extern template class VectorSwizzler<float, 4, 3, 1, 0, 1>;
	extern template class VectorSwizzler<float, 4, 3, 1, 0, 2>;
	extern template class VectorSwizzler<float, 4, 3, 1, 0, 3>;
	extern template class VectorSwizzler<float, 4, 3, 1, 1, 0>;
	extern template class VectorSwizzler<float, 4, 3, 1, 1, 1>;
	extern template class VectorSwizzler<float, 4, 3, 1, 1, 2>;
	extern template class VectorSwizzler<float, 4, 3, 1, 1, 3>;
	extern template class VectorSwizzler<float, 4, 3, 1, 2, 0>;
	extern template class VectorSwizzler<float, 4, 3, 1, 2, 1>;
	extern template class VectorSwizzler<float, 4, 3, 1, 2, 2>;
	extern template class VectorSwizzler<float, 4, 3, 1, 2, 3>;
	extern template class VectorSwizzler<float, 4, 3, 1, 3, 0>;
	extern template class VectorSwizzler<float, 4, 3, 1, 3, 1>;
	extern template class VectorSwizzler<float, 4, 3, 1, 3, 2>;
	extern template class VectorSwizzler<float, 4, 3, 1, 3, 3>;
	extern template class VectorSwizzler<float, 4, 3, 2, 0, 0>;
	extern template class VectorSwizzler<float, 4, 3, 2, 0, 1>;
	extern template class VectorSwizzler<float, 4, 3, 2, 0, 2>;
	extern template class VectorSwizzler<float, 4, 3, 2, 0, 3>;
	extern template class VectorSwizzler<float, 4, 3, 2, 1, 0>;
	extern template class VectorSwizzler<float, 4, 3, 2, 1, 1>;
	extern template class VectorSwizzler<float, 4, 3, 2, 1, 2>;
	extern template class VectorSwizzler<float, 4, 3, 2, 1, 3>;
	extern template class VectorSwizzler<float, 4, 3, 2, 2, 0>;
	extern template class VectorSwizzler<float, 4, 3, 2, 2, 1>;
	extern template class VectorSwizzler<float, 4, 3, 2, 2, 2>;
	extern template class VectorSwizzler<float, 4, 3, 2, 2, 3>;
	extern template class VectorSwizzler<float, 4, 3, 2, 3, 0>;
	extern template class VectorSwizzler<float, 4, 3, 2, 3, 1>;
	extern template class VectorSwizzler<float, 4, 3, 2, 3, 2>;
	extern template class VectorSwizzler<float, 4, 3, 2, 3, 3>;
	extern template class VectorSwizzler<float, 4, 3, 3, 0, 0>;
	extern template class VectorSwizzler<float, 4, 3, 3, 0, 1>;
	extern template class VectorSwizzler<float, 4, 3, 3, 0, 2>;
	extern template class VectorSwizzler<float, 4, 3, 3, 0, 3>;
	extern template class VectorSwizzler<float, 4, 3, 3, 1, 0>;
	extern template class VectorSwizzler<float, 4, 3, 3, 1, 1>;
	extern template class VectorSwizzler<float, 4, 3, 3, 1, 2>;
	extern template class VectorSwizzler<float, 4, 3, 3, 1, 3>;
	extern template class VectorSwizzler<float, 4, 3, 3, 2, 0>;
	extern template class VectorSwizzler<float, 4, 3, 3, 2, 1>;
	extern template class VectorSwizzler<float, 4, 3, 3, 2, 2>;
	extern template class VectorSwizzler<float, 4, 3, 3, 2, 3>;
	extern template class VectorSwizzler<float, 4, 3, 3, 3, 0>;
	extern template class VectorSwizzler<float, 4, 3, 3, 3, 1>;
	extern template class VectorSwizzler<float, 4, 3, 3, 3, 2>;
	extern template class VectorSwizzler<float, 4, 3, 3, 3, 3>;

	extern template class VectorSwizzler<double, 1, 0, 0, 0, 0>;

	extern template class VectorSwizzler<double, 2, 0, 0, 0, 0>;
	extern template class VectorSwizzler<double, 2, 0, 0, 0, 1>;
	extern template class VectorSwizzler<double, 2, 0, 0, 1, 0>;
	extern template class VectorSwizzler<double, 2, 0, 0, 1, 1>;
	extern template class VectorSwizzler<double, 2, 0, 1, 0, 0>;
	extern template class VectorSwizzler<double, 2, 0, 1, 0, 1>;
	extern template class VectorSwizzler<double, 2, 0, 1, 1, 0>;
	extern template class VectorSwizzler<double, 2, 0, 1, 1, 1>;
	extern template class VectorSwizzler<double, 2, 1, 0, 0, 0>;
	extern template class VectorSwizzler<double, 2, 1, 0, 0, 1>;
	extern template class VectorSwizzler<double, 2, 1, 0, 1, 0>;
	extern template class VectorSwizzler<double, 2, 1, 0, 1, 1>;
	extern template class VectorSwizzler<double, 2, 1, 1, 0, 0>;
	extern template class VectorSwizzler<double, 2, 1, 1, 0, 1>;
	extern template class VectorSwizzler<double, 2, 1, 1, 1, 0>;
	extern template class VectorSwizzler<double, 2, 1, 1, 1, 1>;

	extern template class VectorSwizzler<double, 3, 0, 0, 0, 0>;
	extern template class VectorSwizzler<double, 3, 0, 0, 0, 1>;
	extern template class VectorSwizzler<double, 3, 0, 0, 0, 2>;
	extern template class VectorSwizzler<double, 3, 0, 0, 1, 0>;
	extern template class VectorSwizzler<double, 3, 0, 0, 1, 1>;
	extern template class VectorSwizzler<double, 3, 0, 0, 1, 2>;
	extern template class VectorSwizzler<double, 3, 0, 0, 2, 0>;
	extern template class VectorSwizzler<double, 3, 0, 0, 2, 1>;
	extern template class VectorSwizzler<double, 3, 0, 0, 2, 2>;
	extern template class VectorSwizzler<double, 3, 0, 1, 0, 0>;
	extern template class VectorSwizzler<double, 3, 0, 1, 0, 1>;
	extern template class VectorSwizzler<double, 3, 0, 1, 0, 2>;
	extern template class VectorSwizzler<double, 3, 0, 1, 1, 0>;
	extern template class VectorSwizzler<double, 3, 0, 1, 1, 1>;
	extern template class VectorSwizzler<double, 3, 0, 1, 1, 2>;
	extern template class VectorSwizzler<double, 3, 0, 1, 2, 0>;
	extern template class VectorSwizzler<double, 3, 0, 1, 2, 1>;
	extern template class VectorSwizzler<double, 3, 0, 1, 2, 2>;
	extern template class VectorSwizzler<double, 3, 0, 2, 0, 0>;
	extern template class VectorSwizzler<double, 3, 0, 2, 0, 1>;
	extern template class VectorSwizzler<double, 3, 0, 2, 0, 2>;
	extern template class VectorSwizzler<double, 3, 0, 2, 1, 0>;
	extern template class VectorSwizzler<double, 3, 0, 2, 1, 1>;
	extern template class VectorSwizzler<double, 3, 0, 2, 1, 2>;
	extern template class VectorSwizzler<double, 3, 0, 2, 2, 0>;
	extern template class VectorSwizzler<double, 3, 0, 2, 2, 1>;
	extern template class VectorSwizzler<double, 3, 0, 2, 2, 2>;
	extern template class VectorSwizzler<double, 3, 1, 0, 0, 0>;
	extern template class VectorSwizzler<double, 3, 1, 0, 0, 1>;
	extern template class VectorSwizzler<double, 3, 1, 0, 0, 2>;
	extern template class VectorSwizzler<double, 3, 1, 0, 1, 0>;
	extern template class VectorSwizzler<double, 3, 1, 0, 1, 1>;
	extern template class VectorSwizzler<double, 3, 1, 0, 1, 2>;
	extern template class VectorSwizzler<double, 3, 1, 0, 2, 0>;
	extern template class VectorSwizzler<double, 3, 1, 0, 2, 1>;
	extern template class VectorSwizzler<double, 3, 1, 0, 2, 2>;
	extern template class VectorSwizzler<double, 3, 1, 1, 0, 0>;
	extern template class VectorSwizzler<double, 3, 1, 1, 0, 1>;
	extern template class VectorSwizzler<double, 3, 1, 1, 0, 2>;
	extern template class VectorSwizzler<double, 3, 1, 1, 1, 0>;
	extern template class VectorSwizzler<double, 3, 1, 1, 1, 1>;
	extern template class VectorSwizzler<double, 3, 1, 1, 1, 2>;
	extern template class VectorSwizzler<double, 3, 1, 1, 2, 0>;
	extern template class VectorSwizzler<double, 3, 1, 1, 2, 1>;
	extern template class VectorSwizzler<double, 3, 1, 1, 2, 2>;
	extern template class VectorSwizzler<double, 3, 1, 2, 0, 0>;
	extern template class VectorSwizzler<double, 3, 1, 2, 0, 1>;
	extern template class VectorSwizzler<double, 3, 1, 2, 0, 2>;
	extern template class VectorSwizzler<double, 3, 1, 2, 1, 0>;
	extern template class VectorSwizzler<double, 3, 1, 2, 1, 1>;
	extern template class VectorSwizzler<double, 3, 1, 2, 1, 2>;
	extern template class VectorSwizzler<double, 3, 1, 2, 2, 0>;
	extern template class VectorSwizzler<double, 3, 1, 2, 2, 1>;
	extern template class VectorSwizzler<double, 3, 1, 2, 2, 2>;
	extern template class VectorSwizzler<double, 3, 2, 0, 0, 0>;
	extern template class VectorSwizzler<double, 3, 2, 0, 0, 1>;
	extern template class VectorSwizzler<double, 3, 2, 0, 0, 2>;
	extern template class VectorSwizzler<double, 3, 2, 0, 1, 0>;
	extern template class VectorSwizzler<double, 3, 2, 0, 1, 1>;
	extern template class VectorSwizzler<double, 3, 2, 0, 1, 2>;
	extern template class VectorSwizzler<double, 3, 2, 0, 2, 0>;
	extern template class VectorSwizzler<double, 3, 2, 0, 2, 1>;
	extern template class VectorSwizzler<double, 3, 2, 0, 2, 2>;
	extern template class VectorSwizzler<double, 3, 2, 1, 0, 0>;
	extern template class VectorSwizzler<double, 3, 2, 1, 0, 1>;
	extern template class VectorSwizzler<double, 3, 2, 1, 0, 2>;
	extern template class VectorSwizzler<double, 3, 2, 1, 1, 0>;
	extern template class VectorSwizzler<double, 3, 2, 1, 1, 1>;
	extern template class VectorSwizzler<double, 3, 2, 1, 1, 2>;
	extern template class VectorSwizzler<double, 3, 2, 1, 2, 0>;
	extern template class VectorSwizzler<double, 3, 2, 1, 2, 1>;
	extern template class VectorSwizzler<double, 3, 2, 1, 2, 2>;
	extern template class VectorSwizzler<double, 3, 2, 2, 0, 0>;
	extern template class VectorSwizzler<double, 3, 2, 2, 0, 1>;
	extern template class VectorSwizzler<double, 3, 2, 2, 0, 2>;
	extern template class VectorSwizzler<double, 3, 2, 2, 1, 0>;
	extern template class VectorSwizzler<double, 3, 2, 2, 1, 1>;
	extern template class VectorSwizzler<double, 3, 2, 2, 1, 2>;
	extern template class VectorSwizzler<double, 3, 2, 2, 2, 0>;
	extern template class VectorSwizzler<double, 3, 2, 2, 2, 1>;
	extern template class VectorSwizzler<double, 3, 2, 2, 2, 2>;

	extern template class VectorSwizzler<double, 4, 0, 0, 0, 0>;
	extern template class VectorSwizzler<double, 4, 0, 0, 0, 1>;
	extern template class VectorSwizzler<double, 4, 0, 0, 0, 2>;
	extern template class VectorSwizzler<double, 4, 0, 0, 0, 3>;
	extern template class VectorSwizzler<double, 4, 0, 0, 1, 0>;
	extern template class VectorSwizzler<double, 4, 0, 0, 1, 1>;
	extern template class VectorSwizzler<double, 4, 0, 0, 1, 2>;
	extern template class VectorSwizzler<double, 4, 0, 0, 1, 3>;
	extern template class VectorSwizzler<double, 4, 0, 0, 2, 0>;
	extern template class VectorSwizzler<double, 4, 0, 0, 2, 1>;
	extern template class VectorSwizzler<double, 4, 0, 0, 2, 2>;
	extern template class VectorSwizzler<double, 4, 0, 0, 2, 3>;
	extern template class VectorSwizzler<double, 4, 0, 0, 3, 0>;
	extern template class VectorSwizzler<double, 4, 0, 0, 3, 1>;
	extern template class VectorSwizzler<double, 4, 0, 0, 3, 2>;
	extern template class VectorSwizzler<double, 4, 0, 0, 3, 3>;
	extern template class VectorSwizzler<double, 4, 0, 1, 0, 0>;
	extern template class VectorSwizzler<double, 4, 0, 1, 0, 1>;
	extern template class VectorSwizzler<double, 4, 0, 1, 0, 2>;
	extern template class VectorSwizzler<double, 4, 0, 1, 0, 3>;
	extern template class VectorSwizzler<double, 4, 0, 1, 1, 0>;
	extern template class VectorSwizzler<double, 4, 0, 1, 1, 1>;
	extern template class VectorSwizzler<double, 4, 0, 1, 1, 2>;
	extern template class VectorSwizzler<double, 4, 0, 1, 1, 3>;
	extern template class VectorSwizzler<double, 4, 0, 1, 2, 0>;
	extern template class VectorSwizzler<double, 4, 0, 1, 2, 1>;
	extern template class VectorSwizzler<double, 4, 0, 1, 2, 2>;
	extern template class VectorSwizzler<double, 4, 0, 1, 2, 3>;
	extern template class VectorSwizzler<double, 4, 0, 1, 3, 0>;
	extern template class VectorSwizzler<double, 4, 0, 1, 3, 1>;
	extern template class VectorSwizzler<double, 4, 0, 1, 3, 2>;
	extern template class VectorSwizzler<double, 4, 0, 1, 3, 3>;
	extern template class VectorSwizzler<double, 4, 0, 2, 0, 0>;
	extern template class VectorSwizzler<double, 4, 0, 2, 0, 1>;
	extern template class VectorSwizzler<double, 4, 0, 2, 0, 2>;
	extern template class VectorSwizzler<double, 4, 0, 2, 0, 3>;
	extern template class VectorSwizzler<double, 4, 0, 2, 1, 0>;
	extern template class VectorSwizzler<double, 4, 0, 2, 1, 1>;
	extern template class VectorSwizzler<double, 4, 0, 2, 1, 2>;
	extern template class VectorSwizzler<double, 4, 0, 2, 1, 3>;
	extern template class VectorSwizzler<double, 4, 0, 2, 2, 0>;
	extern template class VectorSwizzler<double, 4, 0, 2, 2, 1>;
	extern template class VectorSwizzler<double, 4, 0, 2, 2, 2>;
	extern template class VectorSwizzler<double, 4, 0, 2, 2, 3>;
	extern template class VectorSwizzler<double, 4, 0, 2, 3, 0>;
	extern template class VectorSwizzler<double, 4, 0, 2, 3, 1>;
	extern template class VectorSwizzler<double, 4, 0, 2, 3, 2>;
	extern template class VectorSwizzler<double, 4, 0, 2, 3, 3>;
	extern template class VectorSwizzler<double, 4, 0, 3, 0, 0>;
	extern template class VectorSwizzler<double, 4, 0, 3, 0, 1>;
	extern template class VectorSwizzler<double, 4, 0, 3, 0, 2>;
	extern template class VectorSwizzler<double, 4, 0, 3, 0, 3>;
	extern template class VectorSwizzler<double, 4, 0, 3, 1, 0>;
	extern template class VectorSwizzler<double, 4, 0, 3, 1, 1>;
	extern template class VectorSwizzler<double, 4, 0, 3, 1, 2>;
	extern template class VectorSwizzler<double, 4, 0, 3, 1, 3>;
	extern template class VectorSwizzler<double, 4, 0, 3, 2, 0>;
	extern template class VectorSwizzler<double, 4, 0, 3, 2, 1>;
	extern template class VectorSwizzler<double, 4, 0, 3, 2, 2>;
	extern template class VectorSwizzler<double, 4, 0, 3, 2, 3>;
	extern template class VectorSwizzler<double, 4, 0, 3, 3, 0>;
	extern template class VectorSwizzler<double, 4, 0, 3, 3, 1>;
	extern template class VectorSwizzler<double, 4, 0, 3, 3, 2>;
	extern template class VectorSwizzler<double, 4, 0, 3, 3, 3>;
	extern template class VectorSwizzler<double, 4, 1, 0, 0, 0>;
	extern template class VectorSwizzler<double, 4, 1, 0, 0, 1>;
	extern template class VectorSwizzler<double, 4, 1, 0, 0, 2>;
	extern template class VectorSwizzler<double, 4, 1, 0, 0, 3>;
	extern template class VectorSwizzler<double, 4, 1, 0, 1, 0>;
	extern template class VectorSwizzler<double, 4, 1, 0, 1, 1>;
	extern template class VectorSwizzler<double, 4, 1, 0, 1, 2>;
	extern template class VectorSwizzler<double, 4, 1, 0, 1, 3>;
	extern template class VectorSwizzler<double, 4, 1, 0, 2, 0>;
	extern template class VectorSwizzler<double, 4, 1, 0, 2, 1>;
	extern template class VectorSwizzler<double, 4, 1, 0, 2, 2>;
	extern template class VectorSwizzler<double, 4, 1, 0, 2, 3>;
	extern template class VectorSwizzler<double, 4, 1, 0, 3, 0>;
	extern template class VectorSwizzler<double, 4, 1, 0, 3, 1>;
	extern template class VectorSwizzler<double, 4, 1, 0, 3, 2>;
	extern template class VectorSwizzler<double, 4, 1, 0, 3, 3>;
	extern template class VectorSwizzler<double, 4, 1, 1, 0, 0>;
	extern template class VectorSwizzler<double, 4, 1, 1, 0, 1>;
	extern template class VectorSwizzler<double, 4, 1, 1, 0, 2>;
	extern template class VectorSwizzler<double, 4, 1, 1, 0, 3>;
	extern template class VectorSwizzler<double, 4, 1, 1, 1, 0>;
	extern template class VectorSwizzler<double, 4, 1, 1, 1, 1>;
	extern template class VectorSwizzler<double, 4, 1, 1, 1, 2>;
	extern template class VectorSwizzler<double, 4, 1, 1, 1, 3>;
	extern template class VectorSwizzler<double, 4, 1, 1, 2, 0>;
	extern template class VectorSwizzler<double, 4, 1, 1, 2, 1>;
	extern template class VectorSwizzler<double, 4, 1, 1, 2, 2>;
	extern template class VectorSwizzler<double, 4, 1, 1, 2, 3>;
	extern template class VectorSwizzler<double, 4, 1, 1, 3, 0>;
	extern template class VectorSwizzler<double, 4, 1, 1, 3, 1>;
	extern template class VectorSwizzler<double, 4, 1, 1, 3, 2>;
	extern template class VectorSwizzler<double, 4, 1, 1, 3, 3>;
	extern template class VectorSwizzler<double, 4, 1, 2, 0, 0>;
	extern template class VectorSwizzler<double, 4, 1, 2, 0, 1>;
	extern template class VectorSwizzler<double, 4, 1, 2, 0, 2>;
	extern template class VectorSwizzler<double, 4, 1, 2, 0, 3>;
	extern template class VectorSwizzler<double, 4, 1, 2, 1, 0>;
	extern template class VectorSwizzler<double, 4, 1, 2, 1, 1>;
	extern template class VectorSwizzler<double, 4, 1, 2, 1, 2>;
	extern template class VectorSwizzler<double, 4, 1, 2, 1, 3>;
	extern template class VectorSwizzler<double, 4, 1, 2, 2, 0>;
	extern template class VectorSwizzler<double, 4, 1, 2, 2, 1>;
	extern template class VectorSwizzler<double, 4, 1, 2, 2, 2>;
	extern template class VectorSwizzler<double, 4, 1, 2, 2, 3>;
	extern template class VectorSwizzler<double, 4, 1, 2, 3, 0>;
	extern template class VectorSwizzler<double, 4, 1, 2, 3, 1>;
	extern template class VectorSwizzler<double, 4, 1, 2, 3, 2>;
	extern template class VectorSwizzler<double, 4, 1, 2, 3, 3>;
	extern template class VectorSwizzler<double, 4, 1, 3, 0, 0>;
	extern template class VectorSwizzler<double, 4, 1, 3, 0, 1>;
	extern template class VectorSwizzler<double, 4, 1, 3, 0, 2>;
	extern template class VectorSwizzler<double, 4, 1, 3, 0, 3>;
	extern template class VectorSwizzler<double, 4, 1, 3, 1, 0>;
	extern template class VectorSwizzler<double, 4, 1, 3, 1, 1>;
	extern template class VectorSwizzler<double, 4, 1, 3, 1, 2>;
	extern template class VectorSwizzler<double, 4, 1, 3, 1, 3>;
	extern template class VectorSwizzler<double, 4, 1, 3, 2, 0>;
	extern template class VectorSwizzler<double, 4, 1, 3, 2, 1>;
	extern template class VectorSwizzler<double, 4, 1, 3, 2, 2>;
	extern template class VectorSwizzler<double, 4, 1, 3, 2, 3>;
	extern template class VectorSwizzler<double, 4, 1, 3, 3, 0>;
	extern template class VectorSwizzler<double, 4, 1, 3, 3, 1>;
	extern template class VectorSwizzler<double, 4, 1, 3, 3, 2>;
	extern template class VectorSwizzler<double, 4, 1, 3, 3, 3>;
	extern template class VectorSwizzler<double, 4, 2, 0, 0, 0>;
	extern template class VectorSwizzler<double, 4, 2, 0, 0, 1>;
	extern template class VectorSwizzler<double, 4, 2, 0, 0, 2>;
	extern template class VectorSwizzler<double, 4, 2, 0, 0, 3>;
	extern template class VectorSwizzler<double, 4, 2, 0, 1, 0>;
	extern template class VectorSwizzler<double, 4, 2, 0, 1, 1>;
	extern template class VectorSwizzler<double, 4, 2, 0, 1, 2>;
	extern template class VectorSwizzler<double, 4, 2, 0, 1, 3>;
	extern template class VectorSwizzler<double, 4, 2, 0, 2, 0>;
	extern template class VectorSwizzler<double, 4, 2, 0, 2, 1>;
	extern template class VectorSwizzler<double, 4, 2, 0, 2, 2>;
	extern template class VectorSwizzler<double, 4, 2, 0, 2, 3>;
	extern template class VectorSwizzler<double, 4, 2, 0, 3, 0>;
	extern template class VectorSwizzler<double, 4, 2, 0, 3, 1>;
	extern template class VectorSwizzler<double, 4, 2, 0, 3, 2>;
	extern template class VectorSwizzler<double, 4, 2, 0, 3, 3>;
	extern template class VectorSwizzler<double, 4, 2, 1, 0, 0>;
	extern template class VectorSwizzler<double, 4, 2, 1, 0, 1>;
	extern template class VectorSwizzler<double, 4, 2, 1, 0, 2>;
	extern template class VectorSwizzler<double, 4, 2, 1, 0, 3>;
	extern template class VectorSwizzler<double, 4, 2, 1, 1, 0>;
	extern template class VectorSwizzler<double, 4, 2, 1, 1, 1>;
	extern template class VectorSwizzler<double, 4, 2, 1, 1, 2>;
	extern template class VectorSwizzler<double, 4, 2, 1, 1, 3>;
	extern template class VectorSwizzler<double, 4, 2, 1, 2, 0>;
	extern template class VectorSwizzler<double, 4, 2, 1, 2, 1>;
	extern template class VectorSwizzler<double, 4, 2, 1, 2, 2>;
	extern template class VectorSwizzler<double, 4, 2, 1, 2, 3>;
	extern template class VectorSwizzler<double, 4, 2, 1, 3, 0>;
	extern template class VectorSwizzler<double, 4, 2, 1, 3, 1>;
	extern template class VectorSwizzler<double, 4, 2, 1, 3, 2>;
	extern template class VectorSwizzler<double, 4, 2, 1, 3, 3>;
	extern template class VectorSwizzler<double, 4, 2, 2, 0, 0>;
	extern template class VectorSwizzler<double, 4, 2, 2, 0, 1>;
	extern template class VectorSwizzler<double, 4, 2, 2, 0, 2>;
	extern template class VectorSwizzler<double, 4, 2, 2, 0, 3>;
	extern template class VectorSwizzler<double, 4, 2, 2, 1, 0>;
	extern template class VectorSwizzler<double, 4, 2, 2, 1, 1>;
	extern template class VectorSwizzler<double, 4, 2, 2, 1, 2>;
	extern template class VectorSwizzler<double, 4, 2, 2, 1, 3>;
	extern template class VectorSwizzler<double, 4, 2, 2, 2, 0>;
	extern template class VectorSwizzler<double, 4, 2, 2, 2, 1>;
	extern template class VectorSwizzler<double, 4, 2, 2, 2, 2>;
	extern template class VectorSwizzler<double, 4, 2, 2, 2, 3>;
	extern template class VectorSwizzler<double, 4, 2, 2, 3, 0>;
	extern template class VectorSwizzler<double, 4, 2, 2, 3, 1>;
	extern template class VectorSwizzler<double, 4, 2, 2, 3, 2>;
	extern template class VectorSwizzler<double, 4, 2, 2, 3, 3>;
	extern template class VectorSwizzler<double, 4, 2, 3, 0, 0>;
	extern template class VectorSwizzler<double, 4, 2, 3, 0, 1>;
	extern template class VectorSwizzler<double, 4, 2, 3, 0, 2>;
	extern template class VectorSwizzler<double, 4, 2, 3, 0, 3>;
	extern template class VectorSwizzler<double, 4, 2, 3, 1, 0>;
	extern template class VectorSwizzler<double, 4, 2, 3, 1, 1>;
	extern template class VectorSwizzler<double, 4, 2, 3, 1, 2>;
	extern template class VectorSwizzler<double, 4, 2, 3, 1, 3>;
	extern template class VectorSwizzler<double, 4, 2, 3, 2, 0>;
	extern template class VectorSwizzler<double, 4, 2, 3, 2, 1>;
	extern template class VectorSwizzler<double, 4, 2, 3, 2, 2>;
	extern template class VectorSwizzler<double, 4, 2, 3, 2, 3>;
	extern template class VectorSwizzler<double, 4, 2, 3, 3, 0>;
	extern template class VectorSwizzler<double, 4, 2, 3, 3, 1>;
	extern template class VectorSwizzler<double, 4, 2, 3, 3, 2>;
	extern template class VectorSwizzler<double, 4, 2, 3, 3, 3>;
	extern template class VectorSwizzler<double, 4, 3, 0, 0, 0>;
	extern template class VectorSwizzler<double, 4, 3, 0, 0, 1>;
	extern template class VectorSwizzler<double, 4, 3, 0, 0, 2>;
	extern template class VectorSwizzler<double, 4, 3, 0, 0, 3>;
	extern template class VectorSwizzler<double, 4, 3, 0, 1, 0>;
	extern template class VectorSwizzler<double, 4, 3, 0, 1, 1>;
	extern template class VectorSwizzler<double, 4, 3, 0, 1, 2>;
	extern template class VectorSwizzler<double, 4, 3, 0, 1, 3>;
	extern template class VectorSwizzler<double, 4, 3, 0, 2, 0>;
	extern template class VectorSwizzler<double, 4, 3, 0, 2, 1>;
	extern template class VectorSwizzler<double, 4, 3, 0, 2, 2>;
	extern template class VectorSwizzler<double, 4, 3, 0, 2, 3>;
	extern template class VectorSwizzler<double, 4, 3, 0, 3, 0>;
	extern template class VectorSwizzler<double, 4, 3, 0, 3, 1>;
	extern template class VectorSwizzler<double, 4, 3, 0, 3, 2>;
	extern template class VectorSwizzler<double, 4, 3, 0, 3, 3>;
	extern template class VectorSwizzler<double, 4, 3, 1, 0, 0>;
	extern template class VectorSwizzler<double, 4, 3, 1, 0, 1>;
	extern template class VectorSwizzler<double, 4, 3, 1, 0, 2>;
	extern template class VectorSwizzler<double, 4, 3, 1, 0, 3>;
	extern template class VectorSwizzler<double, 4, 3, 1, 1, 0>;
	extern template class VectorSwizzler<double, 4, 3, 1, 1, 1>;
	extern template class VectorSwizzler<double, 4, 3, 1, 1, 2>;
	extern template class VectorSwizzler<double, 4, 3, 1, 1, 3>;
	extern template class VectorSwizzler<double, 4, 3, 1, 2, 0>;
	extern template class VectorSwizzler<double, 4, 3, 1, 2, 1>;
	extern template class VectorSwizzler<double, 4, 3, 1, 2, 2>;
	extern template class VectorSwizzler<double, 4, 3, 1, 2, 3>;
	extern template class VectorSwizzler<double, 4, 3, 1, 3, 0>;
	extern template class VectorSwizzler<double, 4, 3, 1, 3, 1>;
	extern template class VectorSwizzler<double, 4, 3, 1, 3, 2>;
	extern template class VectorSwizzler<double, 4, 3, 1, 3, 3>;
	extern template class VectorSwizzler<double, 4, 3, 2, 0, 0>;
	extern template class VectorSwizzler<double, 4, 3, 2, 0, 1>;
	extern template class VectorSwizzler<double, 4, 3, 2, 0, 2>;
	extern template class VectorSwizzler<double, 4, 3, 2, 0, 3>;
	extern template class VectorSwizzler<double, 4, 3, 2, 1, 0>;
	extern template class VectorSwizzler<double, 4, 3, 2, 1, 1>;
	extern template class VectorSwizzler<double, 4, 3, 2, 1, 2>;
	extern template class VectorSwizzler<double, 4, 3, 2, 1, 3>;
	extern template class VectorSwizzler<double, 4, 3, 2, 2, 0>;
	extern template class VectorSwizzler<double, 4, 3, 2, 2, 1>;
	extern template class VectorSwizzler<double, 4, 3, 2, 2, 2>;
	extern template class VectorSwizzler<double, 4, 3, 2, 2, 3>;
	extern template class VectorSwizzler<double, 4, 3, 2, 3, 0>;
	extern template class VectorSwizzler<double, 4, 3, 2, 3, 1>;
	extern template class VectorSwizzler<double, 4, 3, 2, 3, 2>;
	extern template class VectorSwizzler<double, 4, 3, 2, 3, 3>;
	extern template class VectorSwizzler<double, 4, 3, 3, 0, 0>;
	extern template class VectorSwizzler<double, 4, 3, 3, 0, 1>;
	extern template class VectorSwizzler<double, 4, 3, 3, 0, 2>;
	extern template class VectorSwizzler<double, 4, 3, 3, 0, 3>;
	extern template class VectorSwizzler<double, 4, 3, 3, 1, 0>;
	extern template class VectorSwizzler<double, 4, 3, 3, 1, 1>;
	extern template class VectorSwizzler<double, 4, 3, 3, 1, 2>;
	extern template class VectorSwizzler<double, 4, 3, 3, 1, 3>;
	extern template class VectorSwizzler<double, 4, 3, 3, 2, 0>;
	extern template class VectorSwizzler<double, 4, 3, 3, 2, 1>;
	extern template class VectorSwizzler<double, 4, 3, 3, 2, 2>;
	extern template class VectorSwizzler<double, 4, 3, 3, 2, 3>;
	extern template class VectorSwizzler<double, 4, 3, 3, 3, 0>;
	extern template class VectorSwizzler<double, 4, 3, 3, 3, 1>;
	extern template class VectorSwizzler<double, 4, 3, 3, 3, 2>;
	extern template class VectorSwizzler<double, 4, 3, 3, 3, 3>;

	#pragma endregion
}
